import { useMemo, useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Pencil, Plus, Trash2 } from "lucide-react"
import { api, useI18n, useToast, Badge, Button, Card, CardContent, CardHeader, CardTitle, Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, Input, Label, Table, TableBody, TableCell, TableHead, TableHeader, TableRow, Textarea } from "@velocelab/dashboard/frontend"

type Tier = { condition?: string; operator?: string; min_tokens: number; price: number }
type TimeTier = { start: string; end: string; price: number }
type TimePricing = { timezone: string; [key: string]: string | TimeTier[] }
type VideoDuration = { seconds: number; price: number }
type VideoResolution = { resolution: string; duration_unit_price: number; durations: VideoDuration[] }
type VideoConfig = { resolutions: VideoResolution[] }
type Price = { id?: number; channel_id: number; model_config_id: number; channel_name?: string; model_name: string; [key: string]: any }
const numericFields = ["input_price", "output_price", "cached_input_price", "cache_write_input_price", "cache_write_1h_input_price", "image_input_price", "image_output_price", "audio_input_price", "audio_output_price"]
const tierFields = ["input_price_tiers", "output_price_tiers", "cached_input_price_tiers", "cache_write_input_price_tiers", "cache_write_1h_input_price_tiers", "image_input_price_tiers", "image_output_price_tiers", "audio_input_price_tiers", "audio_output_price_tiers"]
const timeFields = ["input", "output", "cached_input", "cache_write_input", "cache_write_1h_input", "image_input", "image_output", "audio_input", "audio_output"]
const fieldLabels: Record<string, string> = { input_price: "Input", output_price: "Output", cached_input_price: "Cached input", cache_write_input_price: "Cache write", cache_write_1h_input_price: "Cache write 1h", image_input_price: "Image input", image_output_price: "Image output", audio_input_price: "Audio input", audio_output_price: "Audio output" }
const parse = <T,>(value: unknown, fallback: T): T => { if (typeof value !== "string") return (value as T) ?? fallback; try { return JSON.parse(value) as T } catch { return fallback } }
const emptyTime = (): TimePricing => ({ timezone: "UTC", ...Object.fromEntries(timeFields.map((key) => [key, []])) })
const emptyVideo = (): VideoConfig => ({ resolutions: [] })
function prepare(binding: Price): Price { const next = { ...binding }; for (const key of tierFields) next[key] = parse<Tier[]>(next[key], []); next.time_pricing = parse<TimePricing>(next.time_pricing, emptyTime()); next.video_billing_config = parse<VideoConfig>(next.video_billing_config, emptyVideo()); return next }
function payload(draft: Price): Price { const next = { ...draft }; for (const key of tierFields) next[key] = JSON.stringify(next[key] ?? []); next.time_pricing = JSON.stringify(next.time_pricing ?? emptyTime()); next.video_billing_config = JSON.stringify(next.video_billing_config ?? emptyVideo()); return next }

export default function ModelPrices() {
  const { language } = useI18n(); const zh = language === "zh"; const ja = language === "ja"; const toast = useToast(); const queryClient = useQueryClient(); const [draft, setDraft] = useState<Price | null>(null)
  const prices = useQuery<{ prices: Price[]; currency: string }>({ queryKey: ["billing", "model-prices"], queryFn: async () => (await api.get("/billing/model-prices")).data })
  const rows = useMemo(() => prices.data?.prices ?? [], [prices.data]); const currency = prices.data?.currency ?? "USD"
  const save = useMutation({ mutationFn: async (value: Price) => (await api.post("/billing/model-prices", payload(value))).data, onSuccess: () => { setDraft(null); queryClient.invalidateQueries({ queryKey: ["billing", "model-prices"] }); toast.success(zh ? "价格已保存" : "Price saved") }, onError: () => toast.error(zh ? "价格保存失败" : "Failed to save price") })
  const title = zh ? "模型价格" : "Model prices"
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{zh ? `按渠道-模型绑定配置价格，单位为每百万 Token，货币：${currency}` : `Configure prices per channel-model binding, per million tokens, currency: ${currency}`}</p></div>
    <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent>{prices.isLoading ? <p className="text-sm text-muted-foreground">Loading...</p> : <div className="overflow-x-auto rounded-md border"><Table><TableHeader><TableRow><TableHead>{zh ? "渠道" : "Channel"}</TableHead><TableHead>{zh ? "模型" : "Model"}</TableHead><TableHead>{zh ? "输入" : "Input"}</TableHead><TableHead>{zh ? "输出" : "Output"}</TableHead><TableHead>{zh ? "货币" : "Currency"}</TableHead><TableHead /></TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={`${row.channel_id}:${row.model_config_id}`}><TableCell>{row.channel_name || "-"}</TableCell><TableCell className="font-mono text-sm">{row.model_name}</TableCell><TableCell>{row.input_price}</TableCell><TableCell>{row.output_price}</TableCell><TableCell><Badge variant="outline">{currency}</Badge></TableCell><TableCell className="text-right"><Button variant="ghost" size="icon" title="Edit" onClick={() => setDraft(prepare(row))}><Pencil size={16} /></Button></TableCell></TableRow>)}</TableBody></Table></div>}</CardContent></Card>
    <Dialog open={Boolean(draft)} onOpenChange={(open) => !open && setDraft(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{zh ? "编辑模型价格" : "Edit model price"}</DialogTitle><DialogDescription>{zh ? `价格单位：每 1,000,000 Token；货币由插件配置决定（${currency}）。` : `Per 1,000,000 tokens; currency is controlled by plugin configuration (${currency}).`}</DialogDescription></DialogHeader>{draft && <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><ReadOnly label={zh ? "渠道" : "Channel"} value={draft.channel_name || "-"} /><ReadOnly label={zh ? "模型" : "Model"} value={draft.model_name} /><ReadOnly label={zh ? "绑定" : "Binding"} value={`${draft.channel_id}:${draft.model_config_id}`} /></div><div className="grid gap-4 lg:grid-cols-2">{numericFields.map((key) => <PriceEditor key={key} label={fieldLabels[key]} value={Number(draft[key] || 0)} tiers={draft[`${key}_tiers`] || []} onValue={(value) => setDraft({ ...draft, [key]: value })} onTiers={(value) => setDraft({ ...draft, [`${key}_tiers`]: value })} />)}</div><TimeEditor value={draft.time_pricing} onChange={(value) => setDraft({ ...draft, time_pricing: value })} /><VideoEditor value={draft.video_billing_config} onChange={(value) => setDraft({ ...draft, video_billing_config: value })} /></div>}<DialogFooter><Button variant="outline" onClick={() => setDraft(null)}>{zh ? "取消" : "Cancel"}</Button><Button disabled={!draft || save.isPending} onClick={() => draft && save.mutate(draft)}>{zh ? "保存" : "Save"}</Button></DialogFooter></DialogContent></Dialog></div>
}
function ReadOnly({ label, value }: { label: string; value: string }) { return <div className="space-y-2"><Label>{label}</Label><Input value={value} readOnly className="bg-muted" /></div> }
function PriceEditor({ label, value, tiers, onValue, onTiers }: { label: string; value: number; tiers: Tier[]; onValue: (value: number) => void; onTiers: (value: Tier[]) => void }) { return <section className="space-y-3 rounded-md border bg-muted/20 p-3"><Label>{label} / 1M tokens</Label><Input type="number" min="0" step="any" value={value} onChange={(event) => onValue(Number(event.target.value) || 0)} /><TierEditor tiers={tiers} onChange={onTiers} /></section> }
function TierEditor({ tiers, onChange }: { tiers: Tier[]; onChange: (tiers: Tier[]) => void }) { const add = () => { const min = tiers.reduce((max, item) => Math.max(max, item.min_tokens), 0); onChange([...tiers, { condition: "", operator: ">=", min_tokens: min ? min + 1000000 : 1000000, price: 0 }]) }; return <div className="space-y-2 rounded-md border p-3"><div className="flex items-center justify-between"><span className="text-xs font-medium text-muted-foreground">Tier prices</span><Button type="button" variant="outline" size="sm" className="gap-1" onClick={add}><Plus size={14} />Add tier</Button></div>{tiers.length === 0 ? <div className="text-xs text-muted-foreground">No tiers, using base price</div> : tiers.map((tier, index) => <div key={index} className="grid gap-2 sm:grid-cols-[1fr_80px_1fr_1fr_auto]"><select className="h-9 rounded-md border bg-background px-2 text-sm" value={tier.condition || ""} onChange={(e) => onChange(tiers.map((item, i) => i === index ? { ...item, condition: e.target.value } : item))}><option value="">Current tokens</option><option value="input">Input tokens</option><option value="output">Output tokens</option><option value="cached_input">Cached input</option></select><select className="h-9 rounded-md border bg-background px-2 text-sm" value={tier.operator || ">="} onChange={(e) => onChange(tiers.map((item, i) => i === index ? { ...item, operator: e.target.value } : item))}>{[">=", ">", "<=", "<"].map((op) => <option key={op}>{op}</option>)}</select><Input type="number" value={tier.min_tokens} onChange={(e) => onChange(tiers.map((item, i) => i === index ? { ...item, min_tokens: Number(e.target.value) || 0 } : item))} /><Input type="number" step="any" value={tier.price} onChange={(e) => onChange(tiers.map((item, i) => i === index ? { ...item, price: Number(e.target.value) || 0 } : item))} /><Button type="button" variant="outline" size="icon" title="Delete tier" onClick={() => onChange(tiers.filter((_, i) => i !== index))}><Trash2 size={14} /></Button></div>)}</div> }
function TimeEditor({ value, onChange }: { value: TimePricing; onChange: (value: TimePricing) => void }) { const normalized = { ...emptyTime(), ...(value || {}) } as TimePricing; const [field, setField] = useState(timeFields[0]); const tiers = (normalized[field] as TimeTier[]) || []; const update = (next: TimeTier[]) => onChange({ ...normalized, [field]: next }); return <section className="space-y-3 rounded-md border p-3"><h3 className="font-semibold">Time-based pricing</h3><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-2"><Label>Timezone</Label><Input value={normalized.timezone as string} onChange={(e) => onChange({ ...normalized, timezone: e.target.value })} /></div><div className="space-y-2"><Label>Billing item</Label><select className="h-9 w-full rounded-md border bg-background px-2 text-sm" value={field} onChange={(e) => setField(e.target.value)}>{timeFields.map((item) => <option key={item}>{item}</option>)}</select></div></div>{tiers.map((tier, index) => <div key={index} className="grid gap-2 sm:grid-cols-[1fr_1fr_1fr_auto]"><Input type="time" value={tier.start || "00:00"} onChange={(e) => update(tiers.map((item, i) => i === index ? { ...item, start: e.target.value } : item))} /><Input type="time" value={tier.end || "08:00"} onChange={(e) => update(tiers.map((item, i) => i === index ? { ...item, end: e.target.value } : item))} /><Input type="number" step="any" value={tier.price} onChange={(e) => update(tiers.map((item, i) => i === index ? { ...item, price: Number(e.target.value) || 0 } : item))} /><Button type="button" variant="outline" size="icon" onClick={() => update(tiers.filter((_, i) => i !== index))}><Trash2 size={14} /></Button></div>)}<Button type="button" variant="outline" size="sm" onClick={() => update([...tiers, { start: "00:00", end: "08:00", price: 0 }])}><Plus size={14} className="mr-1" />Add time range</Button></section> }
function VideoEditor({ value, onChange }: { value: VideoConfig; onChange: (value: VideoConfig) => void }) {
  const normalized: VideoConfig = { resolutions: Array.isArray(value?.resolutions) ? value.resolutions.map((item) => ({ resolution: String(item?.resolution ?? "720p"), duration_unit_price: Number(item?.duration_unit_price ?? 0), durations: Array.isArray(item?.durations) ? item.durations : [] })) : [] }
  const patchResolution = (index: number, patch: Partial<VideoResolution>) => onChange({ resolutions: normalized.resolutions.map((item, i) => i === index ? { ...item, ...patch, durations: Array.isArray(patch.durations) ? patch.durations : item.durations } : item) })
  return <section className="space-y-3 rounded-md border p-3"><div className="flex items-center justify-between"><h3 className="font-semibold">Video billing</h3><Button type="button" variant="outline" size="sm" onClick={() => onChange({ resolutions: [...normalized.resolutions, { resolution: "720p", duration_unit_price: 0, durations: [] }] })}><Plus size={14} className="mr-1" />Add resolution</Button></div>{normalized.resolutions.map((resolution, index) => <div key={index} className="space-y-2 rounded-md border bg-muted/20 p-3"><div className="flex gap-2"><Input value={resolution.resolution} onChange={(e) => patchResolution(index, { resolution: e.target.value })} placeholder="720p" /><Button type="button" variant="outline" size="icon" onClick={() => onChange({ resolutions: normalized.resolutions.filter((_, i) => i !== index) })}><Trash2 size={14} /></Button></div><div className="flex items-center justify-between"><span className="text-xs text-muted-foreground">Duration prices</span><Button type="button" variant="outline" size="sm" onClick={() => patchResolution(index, { durations: [...resolution.durations, { seconds: 5, price: 0 }] })}><Plus size={14} className="mr-1" />Add duration</Button></div>{resolution.durations.map((duration, durationIndex) => <div key={durationIndex} className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><Input type="number" value={duration.seconds} onChange={(e) => patchResolution(index, { durations: resolution.durations.map((item, i) => i === durationIndex ? { ...item, seconds: Number(e.target.value) || 0 } : item) })} /><Input type="number" step="any" value={duration.price} onChange={(e) => patchResolution(index, { durations: resolution.durations.map((item, i) => i === durationIndex ? { ...item, price: Number(e.target.value) || 0 } : item) })} /><Button type="button" variant="outline" size="icon" onClick={() => patchResolution(index, { durations: resolution.durations.filter((_, i) => i !== durationIndex) })}><Trash2 size={14} /></Button></div>)}{resolution.durations.length === 0 && <div className="space-y-2"><Label>Duration unit price</Label><Input type="number" step="any" value={resolution.duration_unit_price} onChange={(e) => patchResolution(index, { duration_unit_price: Number(e.target.value) || 0 })} /></div>}</div>)}</section>
}