import { useMemo, useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Pencil } from "lucide-react"
import { api, useI18n, useToast, Badge, Button, Card, CardContent, CardHeader, CardTitle, Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, Input, Label, Table, TableBody, TableCell, TableHead, TableHeader, TableRow, Textarea } from "@velocelab/dashboard/frontend"

type Price = { id?: number; channel_id: number; model_config_id: number; channel_name?: string; model_name: string; [key: string]: string | number | undefined }
const numericFields = ["quota_type", "input_price", "output_price", "cached_input_price", "cache_write_input_price", "cache_write_1h_input_price", "image_input_price", "image_output_price", "audio_input_price", "audio_output_price"]
const tierFields = ["input_price_tiers", "output_price_tiers", "cached_input_price_tiers", "cache_write_input_price_tiers", "cache_write_1h_input_price_tiers", "image_input_price_tiers", "image_output_price_tiers", "audio_input_price_tiers", "audio_output_price_tiers"]
const extraFields = ["time_pricing", "video_billing_config"]
const empty = (binding?: Price): Price => ({ channel_id: binding?.channel_id ?? 0, model_config_id: binding?.model_config_id ?? 0, channel_name: binding?.channel_name ?? "", model_name: binding?.model_name ?? "", ...Object.fromEntries(numericFields.map((key) => [key, binding?.[key] ?? "0"])), ...Object.fromEntries(tierFields.map((key) => [key, binding?.[key] ?? "[]"])), time_pricing: binding?.time_pricing ?? "{}", video_billing_config: binding?.video_billing_config ?? "{}" })
const labels: Record<string, string> = { quota_type: "Quota type (0 token / 1 request)", input_price: "Input", output_price: "Output", cached_input_price: "Cached input", cache_write_input_price: "Cache write", cache_write_1h_input_price: "Cache write 1h", image_input_price: "Image input", image_output_price: "Image output", audio_input_price: "Audio input", audio_output_price: "Audio output", input_price_tiers: "Input tiers", output_price_tiers: "Output tiers", cached_input_price_tiers: "Cached input tiers", cache_write_input_price_tiers: "Cache write tiers", cache_write_1h_input_price_tiers: "Cache write 1h tiers", image_input_price_tiers: "Image input tiers", image_output_price_tiers: "Image output tiers", audio_input_price_tiers: "Audio input tiers", audio_output_price_tiers: "Audio output tiers", time_pricing: "Time pricing", video_billing_config: "Video billing config" }

export default function ModelPrices() {
  const { language } = useI18n(); const zh = language === "zh"; const ja = language === "ja"; const toast = useToast(); const queryClient = useQueryClient(); const [draft, setDraft] = useState<Price | null>(null)
  const prices = useQuery<{ prices: Price[]; currency: string }>({ queryKey: ["billing", "model-prices"], queryFn: async () => (await api.get("/billing/model-prices")).data })
  const rows = useMemo(() => prices.data?.prices ?? [], [prices.data]); const currency = prices.data?.currency ?? "USD"
  const save = useMutation({ mutationFn: async (value: Price) => (await api.post("/billing/model-prices", value)).data, onSuccess: () => { setDraft(null); queryClient.invalidateQueries({ queryKey: ["billing", "model-prices"] }); toast.success(zh ? "价格已保存" : ja ? "価格を保存しました" : "Price saved") }, onError: () => toast.error(zh ? "价格保存失败" : "Failed to save price") })
  const title = zh ? "模型价格" : ja ? "モデル価格" : "Model prices"
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{zh ? `按渠道-模型绑定配置价格，单位为每百万 Token，货币：${currency}` : `Configure prices per channel-model binding, per million tokens, currency: ${currency}`}</p></div>
    <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent>{prices.isLoading ? <p className="text-sm text-muted-foreground">Loading...</p> : <div className="overflow-x-auto rounded-md border"><Table><TableHeader><TableRow><TableHead>{zh ? "渠道" : "Channel"}</TableHead><TableHead>{zh ? "模型" : "Model"}</TableHead><TableHead>{zh ? "输入" : "Input"}</TableHead><TableHead>{zh ? "输出" : "Output"}</TableHead><TableHead>{zh ? "货币" : "Currency"}</TableHead><TableHead /></TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={`${row.channel_id}:${row.model_config_id}`}><TableCell>{row.channel_name || "-"}</TableCell><TableCell className="font-mono text-sm">{row.model_name}</TableCell><TableCell>{row.input_price}</TableCell><TableCell>{row.output_price}</TableCell><TableCell><Badge variant="outline">{currency}</Badge></TableCell><TableCell className="text-right"><Button variant="ghost" size="icon" title="Edit" onClick={() => setDraft(empty(row))}><Pencil size={16} /></Button></TableCell></TableRow>)}</TableBody></Table></div>}</CardContent></Card>
    <Dialog open={Boolean(draft)} onOpenChange={(open) => !open && setDraft(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{zh ? "编辑模型价格" : "Edit model price"}</DialogTitle><DialogDescription>{zh ? `价格单位：每 1,000,000 Token；货币由插件配置决定（${currency}）。` : `Per 1,000,000 tokens; currency is controlled by plugin configuration (${currency}).`}</DialogDescription></DialogHeader>{draft && <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2"><ReadOnly label={zh ? "渠道" : "Channel"} value={draft.channel_name || "-"} /><ReadOnly label={zh ? "模型" : "Model"} value={draft.model_name} /></div><section className="space-y-3"><h3 className="font-semibold">{zh ? "Token 价格" : "Token prices"}</h3><div className="grid gap-3 sm:grid-cols-2">{numericFields.map((key) => <PriceInput key={key} label={labels[key]} value={String(draft[key] ?? "0")} onChange={(value) => setDraft({ ...draft, [key]: value })} />)}</div></section><section className="space-y-3"><h3 className="font-semibold">{zh ? "分层价格 JSON" : "Tier prices JSON"}</h3>{tierFields.map((key) => <JsonInput key={key} label={labels[key]} value={String(draft[key] ?? "[]")} onChange={(value) => setDraft({ ...draft, [key]: value })} />)}</section><section className="space-y-3"><h3 className="font-semibold">{zh ? "时间与视频计费" : "Time and video billing"}</h3>{extraFields.map((key) => <JsonInput key={key} label={labels[key]} value={String(draft[key] ?? "{}")} onChange={(value) => setDraft({ ...draft, [key]: value })} />)}</section></div>}<DialogFooter><Button variant="outline" onClick={() => setDraft(null)}>{zh ? "取消" : "Cancel"}</Button><Button disabled={!draft || save.isPending} onClick={() => draft && save.mutate(draft)}>{zh ? "保存" : "Save"}</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
function ReadOnly({ label, value }: { label: string; value: string }) { return <div className="space-y-2"><Label>{label}</Label><Input value={value} readOnly className="bg-muted" /></div> }
function PriceInput({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) { return <div className="space-y-2"><Label>{label}</Label><Input type="number" min="0" step="any" value={value} onChange={(e) => onChange(e.target.value)} /></div> }
function JsonInput({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) { return <div className="space-y-2"><Label>{label}</Label><Textarea rows={2} value={value} onChange={(e) => onChange(e.target.value)} /></div> }
