export interface HarnessAgent { id?: string; user_id: number; stable_id?: string | null; name: string; prompt: string; default_model: string; user_channel_id?: number | null; stream: boolean; skill_ids: string; mcp_server_ids: string; knowledge_base_ids: string; preset_messages: string; created_at: string; updated_at: string }
export interface HarnessConnectorDevice { id: string; user_id: number; token_hash: string; name: string; remark: string; hostname: string; os: string; arch: string; version: string; kind: string; desktop_instance_id: string; mode: string; status: string; last_seen_at?: string | null; created_at: string; updated_at: string }
export interface HarnessConnectorTask { id: string; user_id: number; device_id: string; run_id: string; action: string; workspace_path: string; payload: string; status: string; result: string; error_message: string; started_at?: string | null; finished_at?: string | null; created_at: string; updated_at: string }
export interface HarnessSession { id: string; user_id: number; folder_id: string; title: string; run_mode: string; agent_id: string; agent_group_id: string; skill_ids: string; mcp_server_ids: string; knowledge_base_ids: string; connector_device_id: string; connector_workspace_path: string; connector_auto_approve: boolean; connector_approval_mode: string; connector_command_prefixes: string; model_name: string; user_channel_id?: number | null; max_tokens: number; temperature?: number | null; reasoning_effort: string; auto_compress_context: boolean; disabled_tool_groups: string; created_at: string; updated_at: string }
export interface HarnessMessage { id: string; session_id: string; user_id: number; role: string; content: string; content_parts: string; tool_calls: string; input_tokens: number; output_tokens: number; sort_order: number; created_at: string; updated_at: string }
export interface HarnessRun { id: string; session_id: string; user_id: number; status: string; assistant_message_id: string; mode: string; status_message: string; current_round: number; error_message: string; cost: string; tool_calls: number; tool_call_details: string; started_at?: string | null; created_at: string; finished_at?: string | null; updated_at: string }
export interface HarnessUserSettings { user_id: number; file_storage_enabled: boolean; assistant_mode_enabled: boolean; custom_mcp_servers: string; title_model_name: string; title_user_channel_id?: number | null; title_generation_scope?: string; connector_approval_agent_id?: string; updated_at: string }
export interface HarnessMCPServer { id: string; user_id: number; name: string; transport: string; command: string; args: string; env: string; url: string; enabled: boolean; created_at: string; updated_at: string }
export interface AdvancedChatFile { id: string; user_id: number; name: string; mime_type: string; size: number; data: string; storage_path: string; text_extract: string; hash: string; source: string; source_key: string; created_at: string; updated_at: string }
export interface AdvancedChatKnowledgeBase { id: string; user_id: number; name: string; description: string; embedding_model_name: string; embedding_user_channel_id: number; created_at: string; updated_at: string }
export interface AdvancedChatMemoryDocument { id: string; user_id: number; scope: string; agent_id: string; group_id: string; kind: string; title: string; storage_path: string; size: number; hash: string; enabled: boolean; updated_by: string; created_at: string; updated_at: string }
export interface AdvancedChatKnowledgeDocument { id: string; knowledge_base_id: string; user_id: number; file_id: string; storage_path: string; name: string; mime_type: string; size: number; text_available: boolean; embedding_status: string; embedding_error: string; embedding_model: string; embedding_dim: number; chunk_count: number; hash: string; embedded_at?: string | null; created_at: string; updated_at: string }
export interface AdvancedChatConnectorCredential { id: string; user_id: number; name: string; type: string; key: string; value: string; created_at: string; updated_at: string }
export interface AdvancedChatConnectorCredentialBinding { id: string; user_id: number; device_id: string; credential_id: string; created_at: string }
export interface AdvancedChatSkillPackage { id: string; user_id: number; name: string; source_name: string; storage_path: string; size: number; file_count: number; hash: string; status: string; error_text: string; created_at: string; updated_at: string }
export interface AdvancedChatPackagedSkill { id: string; user_id: number; package_id: string; name: string; description: string; source: string; skill_path: string; root_path: string; metadata_json: string; allowed_tools: string; compatibility: string; enabled: boolean; size: number; hash: string; created_at: string; updated_at: string }
export interface AdvancedChatKnowledgeChunk { id: string; knowledge_base_id: string; document_id: string; user_id: number; ordinal: number; content: string; content_hash: string; embedding: string; embedding_model: string; embedding_dim: number; created_at: string; updated_at: string }
export interface AdvancedChatRunEvent { id?: number; run_id: string; session_id: string; user_id: number; seq: number; event: string; payload: string; created_at: string }
export interface AdvancedChatChatGroup { id: string; user_id: number; name: string; description: string; connector_device_id: string; connector_workspace_path: string; created_at: string; updated_at: string }
export interface AdvancedChatChatGroupMember { id: string; group_id: string; user_id: number; agent_id: string; agent_name: string; model_name: string; user_channel_id: number; connector_device_id: string; session_id: string; run_id: string; status: string; work_depth: number; created_at: string; updated_at: string }
export interface AdvancedChatChatGroupMessage { id: string; group_id: string; user_id: number; sender_type: string; sender_id: string; sender_name: string; content: string; mention_member_ids: string; depth: number; source_run_id: string; created_at: string }
export interface AdvancedChatPrivateConversation { id: string; group_id: string; user_id: number; member_a_id: string; member_b_id: string; member_a_name: string; member_b_name: string; last_message_at: string; created_at: string; updated_at: string }
export interface AdvancedChatPrivateMessage { id: string; conversation_id: string; group_id: string; user_id: number; sender_member_id: string; sender_name: string; recipient_member_id: string; content: string; source_run_id: string; delivered_at?: string | null; created_at: string }
export interface AdvancedChatScheduledTask { id: string; user_id: number; name: string; description: string; agent_id: string; schedule_type: string; run_at?: string | null; interval_seconds: number; session_mode: string; session_id: string; auto_delete_session: boolean; message: string; timeout_seconds: number; delivery_id: string; model_name: string; user_channel_id: number; max_tokens: number; temperature?: number | null; reasoning_effort: string; enabled: boolean; last_run_at?: string | null; next_run_at?: string | null; last_run_id: string; last_status: string; last_error: string; created_at: string; updated_at: string }
export interface AdvancedChatDelivery { id: string; user_id: number; name: string; description: string; method: string; webhook_url: string; webhook_headers: string; email_to: string; smtp_host: string; smtp_port: string; smtp_username: string; smtp_password: string; smtp_from: string; enabled: boolean; created_at: string; updated_at: string }
export interface AdvancedChatWorkspace { id: string; user_id: number; name: string; location: string; device_id: string; path: string; model: string; agent: string; created_at: string; updated_at: string }
export interface AdvancedChatWorkspaceFile { id: string; workspace_id: string; user_id: number; name: string; content: string; storage_path: string; created_at: string; updated_at: string }
export interface AdvancedChatSessionTask { id: string; user_id: number; session_id: string; position: number; title: string; description: string; status: string; note: string; created_at: string; updated_at: string }
export interface AdvancedChatSessionFolder { id: string; user_id: number; name: string; created_at: string; updated_at: string }
export interface Channel { id?: number; user_channel_id?: number | null; name: string; type: string; base_url: string; api_key: string; plugin_config: string; multiplier: string; priority: number; weight: number; enabled: boolean; price_sync_enabled: boolean; price_sync_cron: string; price_sync_last_at?: string | null; consecutive_failures: number; last_failure_at?: string | null; last_failure_reason: string; auto_disabled_at?: string | null; auto_disabled_reason: string; last_health_checked_at?: string | null; last_health_status: string; created_at: string; updated_at: string }
export interface Model { id?: number; model_name: string; provider: string; provider_icon_url: string; quota_type: number; input_price: string; output_price: string; cached_input_price: string; cache_write_input_price: string; cache_write_1h_input_price: string; image_input_price: string; image_output_price: string; audio_input_price: string; audio_output_price: string; input_price_tiers: string; output_price_tiers: string; cached_input_price_tiers: string; cache_write_input_price_tiers: string; cache_write_1h_input_price_tiers: string; image_input_price_tiers: string; image_output_price_tiers: string; audio_input_price_tiers: string; audio_output_price_tiers: string; video_billing_config: string; enabled: boolean; created_at: string; updated_at: string }
export interface ModelConfig { id?: number; channel_id: number; model_id: number; upstream_model_name: string; input_price: string; output_price: string; enabled: boolean; created_at: string; updated_at: string }
