import { Context } from "yumeri";
import type { AdapterDefinition, AdapterInput, AdapterRegistry } from "@velocelab/adapters";
export const depend = ["adapters"];
export const provide: string[] = [];
function openai(input: AdapterInput, path: string, payload = input.payload) { return { protocol: "openai" as const, path, headers: { "Content-Type": "application/json", Accept: "application/json", ...(input.apiKey ? { Authorization: `Bearer ${input.apiKey}` } : {}) }, payload }; }
const deepseek: AdapterDefinition = { types: ["deepseek", "deep_seek"], request: (input) => { const payload = { ...input.payload }; const match = String(payload.model ?? "").match(/^(.*?)-(high|medium|low|thinking|reasoner)$/); if (match) { payload.model = match[1]; payload.thinking = { type: "enabled" }; payload.reasoning_effort = match[2] === "thinking" || match[2] === "reasoner" ? "medium" : match[2]; } return openai(input, input.endpoint === "claude_messages" ? "/anthropic/v1/messages" : "/v1/chat/completions", payload); } };
const dashscope: AdapterDefinition = { types: ["ali", "dashscope", "qwen", "aliyun"], request: (input) => { const payload = { ...input.payload }; if (input.endpoint === "chat" && payload.stream === true) payload.stream_options = { ...(payload.stream_options as object ?? {}), include_usage: true }; const paths: Record<string, string> = { chat: "/compatible-mode/v1/chat/completions", responses: "/api/v2/apps/protocols/compatible-mode/v1/responses", claude_messages: "/apps/anthropic/v1/messages", image_generation: "/api/v1/services/aigc/text2image/image-synthesis", image_edit: "/api/v1/services/aigc/image2image/image-synthesis" }; return openai(input, paths[input.endpoint] ?? paths.chat, payload); } };
const zhipu: AdapterDefinition = { types: ["zhipu", "zhipu_v4", "bigmodel", "glm"], request: (input) => { const payload = { ...input.payload }; if (input.endpoint === "chat" && Number(payload.top_p) >= 1) payload.top_p = 0.99; const paths: Record<string, string> = { chat: "/api/paas/v4/chat/completions", claude_messages: "/api/anthropic/v1/messages", image_generation: "/api/paas/v4/images/generations" }; return openai(input, paths[input.endpoint] ?? paths.chat, payload); } };
const xai: AdapterDefinition = { types: ["xai", "x_ai", "grok"], request: (input) => { const payload = { ...input.payload }; let model = String(payload.model ?? ""); if (model.endsWith("-search")) { model = model.slice(0, -7); payload.search_parameters = { mode: "on" }; } const effort = model.match(/-(high|low)$/)?.[1]; if (effort) { model = model.slice(0, -(effort.length + 1)); payload.reasoning_effort = effort; } payload.model = model; return openai(input, "/v1/chat/completions", payload); } };
const moonshot: AdapterDefinition = { types: ["moonshot", "kimi"], request: (input) => { const payload = { ...input.payload }; if (input.endpoint === "chat" && String(payload.model).toLowerCase() === "kimi-k2.6") payload.temperature = 1; return openai(input, input.endpoint === "claude_messages" ? "/anthropic/v1/messages" : "/v1/chat/completions", payload); } };
const siliconflow: AdapterDefinition = { types: ["siliconflow", "silicon_flow"], request: (input) => { const payload = { ...input.payload }; if (input.endpoint === "image_generation") { if (payload.size !== undefined) { payload.image_size ??= payload.size; delete payload.size; } if (payload.n !== undefined) { payload.batch_size ??= payload.n; delete payload.n; } } return openai(input, "/v1/chat/completions", payload); } };
export function apply(ctx: Context) { const registry = ctx.component.adapters as AdapterRegistry; for (const adapter of [deepseek, dashscope, zhipu, xai, moonshot, siliconflow]) registry.register(adapter); }
