import { Ionicons } from "@expo/vector-icons"
import { useCallback, useEffect, useState } from "react"
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native"
import { request } from "../api"
import type { Palette } from "../theme"
import type { Agent } from "../types"

export default function AgentsHomePage({ colors, onOpen }: { colors: Palette; onOpen: (agent: Agent) => void }) {
  const [agents, setAgents] = useState<Agent[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("")
  const load = useCallback(async () => { setLoading(true); try { const data = await request<Agent[]>("/user/advanced-chat/agents"); setAgents(Array.isArray(data) ? data : []) } catch (e) { setError(e instanceof Error ? e.message : "加载智能体失败") } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  return <View style={styles.root}><View style={[styles.header, { borderColor: colors.border }]}><View><Text style={[styles.title, { color: colors.text }]}>智能体</Text><Text style={{ color: colors.muted, fontSize: 12 }}>选择一个智能体开始对话</Text></View><Pressable onPress={() => void load()} hitSlop={10} style={({ pressed }) => pressed && styles.pressed}><Ionicons name="refresh-outline" size={22} color={colors.text} /></Pressable></View>{error ? <Text style={{ color: colors.destructive, paddingHorizontal: 16, paddingTop: 12 }}>{error}</Text> : null}<FlatList data={agents} keyExtractor={item => item.id} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} />} contentContainerStyle={styles.list} ListEmptyComponent={loading ? <ActivityIndicator color={colors.muted} /> : <View style={styles.empty}><Ionicons name="hardware-chip-outline" size={34} color={colors.muted} /><Text style={{ color: colors.muted }}>暂无可用智能体</Text></View>} renderItem={({ item }) => <Pressable onPress={() => onOpen(item)} android_ripple={{ color: colors.input }} style={({ pressed }) => [styles.row, { borderColor: colors.border, backgroundColor: colors.card }, pressed && styles.pressed]}><View style={[styles.avatar, { backgroundColor: colors.input }]}><Ionicons name="hardware-chip-outline" size={22} color={colors.text} /></View><View style={{ flex: 1, gap: 3 }}><Text style={{ color: colors.text, fontWeight: "600", fontSize: 16 }}>{item.name}</Text><Text style={{ color: colors.muted, fontSize: 12 }} numberOfLines={2}>{item.prompt || item.default_model || "开始与这个智能体对话"}</Text></View><Ionicons name="chevron-forward" size={19} color={colors.muted} /></Pressable>} /></View>
}

const styles = StyleSheet.create({ root: { flex: 1 }, header: { minHeight: 68, paddingHorizontal: 16, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, title: { fontSize: 22, fontWeight: "700" }, list: { padding: 16, gap: 10, flexGrow: 1 }, row: { minHeight: 76, borderWidth: 1, borderRadius: 14, padding: 12, flexDirection: "row", alignItems: "center", gap: 12 }, avatar: { width: 46, height: 46, borderRadius: 14, alignItems: "center", justifyContent: "center" }, pressed: { opacity: .58, transform: [{ scale: .985 }] }, empty: { flex: 1, minHeight: 260, justifyContent: "center", alignItems: "center", gap: 10 } })
