import { Ionicons } from "@expo/vector-icons"
import { useCallback, useEffect, useState } from "react"
import { Alert, FlatList, Modal, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native"
import { request } from "../api"
import type { Palette } from "../theme"

type ExploreKind = "agents" | "knowledge" | "groups" | "skills" | "mcp"
type Props = { colors: Palette }

const config: Record<ExploreKind, { label: string; endpoint: string; icon: keyof typeof Ionicons.glyphMap }> = {
  agents: { label: "智能体", endpoint: "/user/advanced-chat/agents", icon: "hardware-chip-outline" }, knowledge: { label: "知识库", endpoint: "/user/advanced-chat/knowledge-bases", icon: "library-outline" }, groups: { label: "聊天群组", endpoint: "/user/advanced-chat/chat-groups", icon: "people-outline" }, skills: { label: "技能", endpoint: "/user/advanced-chat/skills", icon: "sparkles-outline" }, mcp: { label: "MCP", endpoint: "/user/advanced-chat/settings", icon: "extension-puzzle-outline" },
}

export default function ExplorePage({ colors }: Props) {
  const [kind, setKind] = useState<ExploreKind>("agents")
  const [items, setItems] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [editor, setEditor] = useState(false)
  const [name, setName] = useState("")
  const [description, setDescription] = useState("")
  const [selected, setSelected] = useState<any | null>(null)
  const [detail, setDetail] = useState<any | null>(null)
  const [detailDraft, setDetailDraft] = useState("")
  const [groupDraft, setGroupDraft] = useState("")
  const [groupSending, setGroupSending] = useState(false)
  const load = useCallback(async () => { setLoading(true); try { const data = await request<any>(config[kind].endpoint); const next = kind === "knowledge" ? data?.knowledge_bases || data : kind === "mcp" ? [...(data?.builtin_mcp_servers || []), ...(data?.custom_mcp_servers || []), ...(data?.mcp_servers || [])] : data; setItems(Array.isArray(next) ? next : []) } catch (e) { setError(message(e)); setItems([]) } finally { setLoading(false) } }, [kind])
  useEffect(() => { void load() }, [load])
  const canCreate = kind === "agents" || kind === "knowledge" || kind === "groups"
  const create = async () => { if (!name.trim()) return; try { const body = kind === "agents" ? { name: name.trim(), prompt: description.trim(), default_model: "", stream: true, skill_ids: [], mcp_server_ids: [], knowledge_base_ids: [] } : kind === "knowledge" ? { name: name.trim(), description: description.trim() } : { name: name.trim(), description: description.trim(), agent_ids: [] }; await request(config[kind].endpoint, { method: "POST", body }); setEditor(false); setName(""); setDescription(""); await load() } catch (e) { setError(message(e)) } }
  const open = async (item: any) => { setSelected(item); setDetailDraft(String(item.prompt || item.description || "")); if (kind === "groups") { try { setDetail(await request<any>(`/user/advanced-chat/chat-groups/${encodeURIComponent(item.id)}`)) } catch (e) { setError(message(e)) } } else setDetail(item) }
  const saveDetail = async () => { if (!selected || !detailDraft.trim() || (kind !== "agents" && kind !== "knowledge")) return; try { const path = kind === "agents" ? `/user/advanced-chat/agents/${encodeURIComponent(selected.id)}` : `/user/advanced-chat/knowledge-bases/${encodeURIComponent(selected.id)}`; const body = kind === "agents" ? { name: selected.name, prompt: detailDraft.trim(), default_model: selected.default_model || "", stream: selected.stream !== false, skill_ids: selected.skill_ids || [], mcp_server_ids: selected.mcp_server_ids || [], knowledge_base_ids: selected.knowledge_base_ids || [] } : { name: selected.name, description: detailDraft.trim() }; await request(path, { method: "PUT", body }); setDetail(null); await load() } catch (e) { setError(message(e)) } }
  const sendGroup = async () => { if (!selected || !groupDraft.trim() || groupSending) return; setGroupSending(true); try { await request(`/user/advanced-chat/chat-groups/${encodeURIComponent(selected.id)}/messages`, { method: "POST", body: { content: groupDraft.trim(), mention_member_ids: [] } }); setGroupDraft(""); setDetail(await request<any>(`/user/advanced-chat/chat-groups/${encodeURIComponent(selected.id)}`)) } catch (e) { setError(message(e)) } finally { setGroupSending(false) } }
  return <><View style={styles.flex}><PageHeader colors={colors} title="工作台" /><View style={[styles.segment, { borderColor: colors.border }]}>{(Object.keys(config) as ExploreKind[]).map(key => <Pressable key={key} onPress={() => setKind(key)} style={[styles.segmentItem, kind === key && { backgroundColor: colors.primary }]}><Ionicons name={config[key].icon} size={16} color={kind === key ? colors.primaryText : colors.muted} /><Text style={[styles.segmentLabel, { color: kind === key ? colors.primaryText : colors.muted }]}>{config[key].label}</Text></Pressable>)}</View><ResourceList colors={colors} title={config[kind].label} items={items} loading={loading} error={error} onRefresh={load} onCreate={canCreate ? () => setEditor(true) : undefined} onSelect={open} icon={config[kind].icon} /></View><Modal visible={editor} transparent animationType="slide"><Sheet colors={colors} title={`新建${config[kind].label}`} onClose={() => setEditor(false)}><Field colors={colors} placeholder="名称" value={name} onChangeText={setName} /><Field colors={colors} placeholder={kind === "agents" ? "系统提示词（可选）" : "说明（可选）"} value={description} onChangeText={setDescription} multiline /><Button colors={colors} title="创建" onPress={create} disabled={!name.trim()} /></Sheet></Modal><Modal visible={Boolean(detail)} transparent animationType="slide"><Sheet colors={colors} title={selected?.name || "详情"} onClose={() => setDetail(null)}>{kind === "groups" ? <><ScrollView style={styles.detailScroll}>{(detail?.messages || []).map((item: any, index: number) => <View key={item.id || index} style={[styles.groupMessage, { backgroundColor: colors.bubble }]}><Text style={[styles.resourceName, { color: colors.text }]}>{item.sender_name || "成员"}</Text><Text style={[styles.messageText, { color: colors.text }]}>{item.content}</Text></View>)}</ScrollView><Field colors={colors} placeholder="发送群消息" value={groupDraft} onChangeText={setGroupDraft} multiline /><Button colors={colors} title={groupSending ? "发送中" : "发送"} onPress={sendGroup} disabled={groupSending || !groupDraft.trim()} /></> : <><Field colors={colors} value={detailDraft} onChangeText={setDetailDraft} multiline /><Button colors={colors} title="保存修改" onPress={saveDetail} disabled={!detailDraft.trim()} /></>}</Sheet></Modal></>
}

function ResourceList({ colors, title, items, loading, error, onRefresh, onCreate, onSelect, icon }: any) { return <FlatList style={styles.flex} contentContainerStyle={styles.listContent} data={items} keyExtractor={(item, index) => String(item.id || item.name || index)} refreshControl={<RefreshControl refreshing={loading} onRefresh={onRefresh} tintColor={colors.muted} />} ListHeaderComponent={<View style={styles.listHeader}><View><Text style={[styles.pageTitle, { color: colors.text }]}>{title}</Text><Text style={[styles.small, { color: colors.muted }]}>{items.length} 项</Text></View>{onCreate ? <Button colors={colors} title="新建" onPress={onCreate} /> : null}</View>} ListEmptyComponent={loading ? <Loading colors={colors} /> : <Empty colors={colors} icon={icon} text={error || `暂无${title}`} />} renderItem={({ item }) => <Pressable onPress={onSelect ? () => onSelect(item) : undefined} style={[styles.resourceRow, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.resourceIcon, { backgroundColor: colors.input }]}><Ionicons name={icon} size={20} color={colors.text} /></View><View style={styles.resourceText}><Text style={[styles.resourceName, { color: colors.text }]} numberOfLines={1}>{item.name || item.title || item.hostname || item.id || "未命名"}</Text><Text style={[styles.resourceDetail, { color: colors.muted }]} numberOfLines={2}>{String(item.description || item.default_model || item.type || item.status || "")}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted} /></Pressable>} /> }
function PageHeader({ colors, title }: any) { return <View style={[styles.header, { borderColor: colors.border }]}><Text style={[styles.headerTitle, { color: colors.text }]}>{title}</Text></View> }
function Field({ colors, multiline, ...props }: any) { return <TextInput {...props} multiline={multiline} placeholderTextColor={colors.muted} style={[styles.field, multiline && styles.fieldMultiline, { color: colors.text, borderColor: colors.border, backgroundColor: colors.input }]} /> }
function Button({ colors, title, onPress, disabled }: any) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.button, { backgroundColor: colors.primary, opacity: disabled ? .45 : 1 }]}><Text style={styles.buttonText}>{title}</Text></Pressable> }
function Sheet({ colors, title, children, onClose }: any) { return <View style={styles.modalPosition}><Pressable style={styles.modalBackdrop} onPress={onClose} /><View style={[styles.sheet, { backgroundColor: colors.card }]}><View style={styles.sheetHeader}><Text style={[styles.sheetTitle, { color: colors.text }]}>{title}</Text><Pressable onPress={onClose}><Ionicons name="close" size={22} color={colors.text} /></Pressable></View>{children}</View></View> }
function Empty({ colors, icon, text }: any) { return <View style={styles.empty}><Ionicons name={icon} size={32} color={colors.muted} /><Text style={[styles.emptyText, { color: colors.muted }]}>{text}</Text></View> }
function Loading({ colors }: any) { return <View style={styles.loading}><Text style={{ color: colors.muted }}>加载中…</Text></View> }
function message(error: unknown) { return error instanceof Error ? error.message : "发生未知错误" }

const styles = StyleSheet.create({ flex: { flex: 1 }, header: { height: 58, borderBottomWidth: StyleSheet.hairlineWidth, justifyContent: "center", paddingHorizontal: 16 }, headerTitle: { fontSize: 18, fontWeight: "600" }, segment: { borderBottomWidth: StyleSheet.hairlineWidth, padding: 8, flexDirection: "row", gap: 4 }, segmentItem: { flex: 1, borderRadius: 9, alignItems: "center", justifyContent: "center", height: 42, gap: 2 }, segmentLabel: { fontSize: 10 }, listContent: { padding: 16, gap: 10, paddingBottom: 24, flexGrow: 1 }, listHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 2 }, pageTitle: { fontSize: 24, fontWeight: "700" }, small: { fontSize: 12 }, resourceRow: { minHeight: 70, borderWidth: 1, borderRadius: 14, padding: 12, flexDirection: "row", alignItems: "center", gap: 12 }, resourceIcon: { width: 42, height: 42, borderRadius: 12, alignItems: "center", justifyContent: "center" }, resourceText: { flex: 1 }, resourceName: { fontSize: 15, fontWeight: "600" }, resourceDetail: { fontSize: 12, marginTop: 4 }, button: { minHeight: 44, paddingHorizontal: 16, borderRadius: 10, alignItems: "center", justifyContent: "center" }, buttonText: { color: "#fff", fontWeight: "600" }, field: { minHeight: 48, borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, fontSize: 16 }, fieldMultiline: { minHeight: 100, textAlignVertical: "top" }, modalPosition: { flex: 1, justifyContent: "flex-end" }, modalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,.36)" }, sheet: { padding: 20, paddingBottom: 32, borderTopLeftRadius: 24, borderTopRightRadius: 24, gap: 14, maxHeight: "85%" }, sheetHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, sheetTitle: { fontSize: 20, fontWeight: "700" }, detailScroll: { maxHeight: 300 }, groupMessage: { borderRadius: 10, padding: 10, marginBottom: 8 }, messageText: { fontSize: 15, lineHeight: 22 }, empty: { alignItems: "center", justifyContent: "center", padding: 40, gap: 12 }, emptyText: { fontSize: 14, textAlign: "center" }, loading: { alignItems: "center", justifyContent: "center", minHeight: 120 } })
