import { Ionicons } from "@expo/vector-icons"
import * as DocumentPicker from "expo-document-picker"
import { useCallback, useEffect, useState } from "react"
import { Alert, FlatList, Modal, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native"
import { request, uploadFile } from "../api"
import type { Palette } from "../theme"
import { Top } from "./TasksPage"

export default function FilesPage({ colors, onBack }: { colors: Palette; onBack: () => void }) {
  const [items, setItems] = useState<any[]>([]); const [selected, setSelected] = useState<string[]>([]); const [uploading, setUploading] = useState(false); const [preview, setPreview] = useState<{ name: string; content: string; truncated: boolean } | null>(null); const [error, setError] = useState("")
  const load = useCallback(async () => { try { const data = await request<any>("/user/advanced-chat/files"); setItems(Array.isArray(data?.files) ? data.files : Array.isArray(data) ? data : []) } catch (e) { setError(message(e)) } }, [])
  useEffect(() => { void load() }, [load])
  const upload = async () => { if (uploading) return; const picked = await DocumentPicker.getDocumentAsync({ multiple: true, copyToCacheDirectory: false }); if (picked.canceled) return; setUploading(true); try { for (const asset of picked.assets) await uploadFile("/user/advanced-chat/files", asset); await load() } catch (e) { setError(message(e)) } finally { setUploading(false) } }
  const removeSelected = () => { if (!selected.length) return; Alert.alert("批量删除", `确定删除选中的 ${selected.length} 个文件？`, [{ text: "取消", style: "cancel" }, { text: "删除", style: "destructive", onPress: async () => { try { await Promise.all(selected.map(id => request(`/user/advanced-chat/files/${encodeURIComponent(id)}`, { method: "DELETE" }))); setSelected([]); await load() } catch (e) { setError(message(e)) } } }]) }
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id])
  const previewSelected = async () => { const item = items.find(file => file.id === selected[0]); if (!item) return; try { const data = await request<any>(`/user/advanced-chat/files/${encodeURIComponent(item.id)}/content`); setPreview({ name: item.name || "文件内容", content: typeof data?.content === "string" ? data.content : "", truncated: data?.truncated === true }) } catch (e) { setError(message(e)) } }
  return <View style={styles.root}><Top colors={colors} title="文件库" onBack={onBack} right="" /><View style={[styles.actions, { borderBottomColor: colors.border }]}><Pressable onPress={upload}><Text style={{ color: colors.text }}>{uploading ? "上传中…" : "上传文件"}</Text></Pressable><Pressable onPress={() => setSelected(selected.length === items.length ? [] : items.map(item => item.id))}><Text style={{ color: colors.text }}>{selected.length === items.length && items.length ? "取消全选" : "全选"}</Text></Pressable><Pressable disabled={selected.length !== 1} onPress={previewSelected}><Text style={{ color: selected.length === 1 ? colors.text : colors.muted }}>查看</Text></Pressable><Pressable disabled={!selected.length} onPress={removeSelected}><Text style={{ color: selected.length ? colors.destructive : colors.muted }}>删除 {selected.length || ""}</Text></Pressable></View>{error ? <Text style={{ color: colors.destructive, padding: 12 }}>{error}</Text> : null}<FlatList data={items} keyExtractor={item => item.id} refreshControl={<RefreshControl refreshing={false} onRefresh={load} />} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={{ color: colors.muted }}>暂无文件</Text>} renderItem={({ item }) => <Pressable onPress={() => toggle(item.id)} style={[styles.row, { borderColor: colors.border, backgroundColor: selected.includes(item.id) ? colors.input : colors.card }]}><Ionicons name={selected.includes(item.id) ? "checkbox-outline" : "square-outline"} size={20} color={colors.text} /><Ionicons name="document-text-outline" size={21} color={colors.text} /><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontWeight: "600" }} numberOfLines={1}>{item.name}</Text><Text style={{ color: colors.muted, fontSize: 12 }}>{item.type || "文件"} · {formatBytes(item.size || 0)}</Text></View>{item.text_available ? <Text style={{ color: colors.muted, fontSize: 12 }}>文本</Text> : null}</Pressable>} /><Modal visible={Boolean(preview)} transparent animationType="slide" onRequestClose={() => setPreview(null)}><View style={styles.modal}><Pressable style={StyleSheet.absoluteFill} onPress={() => setPreview(null)} /><View style={[styles.previewSheet, { backgroundColor: colors.card }]}><View style={styles.previewHeader}><Text style={{ color: colors.text, fontSize: 18, fontWeight: "700", flex: 1 }} numberOfLines={1}>{preview?.name}</Text><Pressable onPress={() => setPreview(null)}><Text style={{ color: colors.text }}>关闭</Text></Pressable></View><ScrollView contentContainerStyle={styles.previewContent}><Text selectable style={[styles.previewText, { color: colors.text }]}>{preview?.content || "文件内容为空或不可读取。"}</Text>{preview?.truncated ? <Text style={{ color: colors.muted, fontSize: 12 }}>内容已截断</Text> : null}</ScrollView></View></View></Modal></View>
}
function formatBytes(value: number) { if (value < 1024) return `${value} B`; if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`; return `${(value / 1024 / 1024).toFixed(1)} MB` }
function message(error: unknown) { return error instanceof Error ? error.message : "发生未知错误" }
const styles = StyleSheet.create({ root: { flex: 1 }, actions: { minHeight: 46, paddingHorizontal: 15, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, list: { padding: 15, gap: 9 }, row: { minHeight: 66, borderWidth: 1, borderRadius: 11, padding: 11, flexDirection: "row", alignItems: "center", gap: 10 }, modal: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,.36)" }, previewSheet: { maxHeight: "86%", minHeight: "56%", borderTopLeftRadius: 22, borderTopRightRadius: 22, padding: 18 }, previewHeader: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 12 }, previewContent: { paddingBottom: 24, gap: 10 }, previewText: { fontFamily: "monospace", fontSize: 12, lineHeight: 19 } })
