import { Ionicons } from "@expo/vector-icons"
import { useCallback, useEffect, useRef, useState } from "react"
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native"
import { request } from "../api"
import type { Palette } from "../theme"
import { Top } from "./TasksPage"

export default function GroupChatPage({ colors, groupID, onBack }: { colors: Palette; groupID: string; onBack: () => void }) {
  const [detail, setDetail] = useState<any>(null); const [draft, setDraft] = useState(""); const [sending, setSending] = useState(false); const scroll = useRef<ScrollView>(null)
  const load = useCallback(async () => { try { setDetail(await request<any>(`/user/advanced-chat/chat-groups/${encodeURIComponent(groupID)}`)) } catch { setDetail(null) } }, [groupID])
  useEffect(() => { void load() }, [load])
  const send = async () => { if (!draft.trim() || sending) return; setSending(true); try { await request(`/user/advanced-chat/chat-groups/${encodeURIComponent(groupID)}/messages`, { method: "POST", body: { content: draft.trim(), mention_member_ids: [] } }); setDraft(""); await load() } finally { setSending(false) } }
  return <View style={styles.root}><Top colors={colors} title={detail?.group?.name || "群组"} onBack={onBack} right="" /><View style={[styles.members, { borderBottomColor: colors.border }]}>{(detail?.group?.members || []).map((member: any) => <View key={member.id} style={[styles.member, { backgroundColor: colors.input }]}><View style={[styles.dot, { backgroundColor: member.status === "working" ? "#22c55e" : colors.muted }]} /><Text style={{ color: colors.text, fontSize: 12 }}>{member.agent_name || member.agent_id}</Text></View>)}</View><ScrollView ref={scroll} style={styles.flex} contentContainerStyle={styles.messages}>{detail?.messages?.map((item: any, index: number) => <View key={item.id || index} style={[styles.message, { backgroundColor: item.sender_type === "user" ? colors.primary : colors.bubble, alignSelf: item.sender_type === "user" ? "flex-end" : "flex-start" }]}><Text style={{ color: item.sender_type === "user" ? colors.primaryText : colors.muted, fontSize: 12 }}>{item.sender_name || "成员"}</Text><Text style={{ color: item.sender_type === "user" ? colors.primaryText : colors.text, fontSize: 16, lineHeight: 23 }}>{item.content}</Text></View>) || <ActivityIndicator color={colors.muted} />}</ScrollView><View style={[styles.composer, { borderColor: colors.border, backgroundColor: colors.card }]}><TextInput value={draft} onChangeText={setDraft} multiline placeholder="发送群消息" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.text, backgroundColor: colors.input }]} /><Pressable onPress={send} disabled={sending}><Ionicons name="arrow-up-circle" size={30} color={colors.text} /></Pressable></View></View>
}
const styles = StyleSheet.create({ root: { flex: 1 }, flex: { flex: 1 }, members: { flexDirection: "row", gap: 7, padding: 9, borderBottomWidth: StyleSheet.hairlineWidth }, member: { borderRadius: 14, paddingHorizontal: 8, paddingVertical: 5, flexDirection: "row", gap: 5, alignItems: "center" }, dot: { width: 7, height: 7, borderRadius: 4 }, messages: { padding: 14, gap: 10, flexGrow: 1 }, message: { maxWidth: "86%", borderRadius: 14, padding: 11, gap: 4 }, composer: { borderTopWidth: StyleSheet.hairlineWidth, padding: 10, flexDirection: "row", alignItems: "flex-end", gap: 8 }, input: { flex: 1, minHeight: 44, maxHeight: 120, borderRadius: 14, paddingHorizontal: 12, paddingVertical: 10, fontSize: 16 } })
