import { useCallback, useEffect, useState } from "react"
import { Alert, BackHandler, FlatList, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native"
import { request } from "../api"
import type { Palette } from "../theme"
import { Action, Input, Sheet, Top } from "./TasksPage"

type KnowledgeBase = Record<string, any>
type KnowledgeDocument = Record<string, any>

export default function KnowledgeBasesPage({ colors, onBack }: { colors: Palette; onBack: () => void }) {
  const [bases, setBases] = useState<KnowledgeBase[]>([]); const [selected, setSelected] = useState<KnowledgeBase | null>(null); const [documents, setDocuments] = useState<KnowledgeDocument[]>([]); const [editing, setEditing] = useState<KnowledgeDocument | null>(null); const [content, setContent] = useState(""); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [modal, setModal] = useState<"base" | "document" | "" >(""); const [error, setError] = useState("")
  const loadBases = useCallback(async () => { try { const data = await request<any>("/user/advanced-chat/knowledge-bases"); setBases(Array.isArray(data?.knowledge_bases) ? data.knowledge_bases : []) } catch (e) { setError(message(e)) } }, [])
  const loadDocuments = useCallback(async (base: KnowledgeBase) => { try { const data = await request<any>(`/user/advanced-chat/knowledge-bases/${encodeURIComponent(base.id)}/documents`); setDocuments(Array.isArray(data?.documents) ? data.documents : []) } catch (e) { setError(message(e)) } }, [])
  useEffect(() => { void loadBases() }, [loadBases])
  useEffect(() => { if (!selected || editing) return; void loadDocuments(selected) }, [selected, editing, loadDocuments])
  useEffect(() => { if (!editing) return; const subscription = BackHandler.addEventListener("hardwareBackPress", () => { setEditing(null); setContent(""); return true }); return () => subscription.remove() }, [editing])
  const openBase = (base: KnowledgeBase) => { setSelected(base); setDocuments([]); setError("") }
  const saveBase = async () => { if (!name.trim()) { setError("请输入知识库名称"); return } try { await request("/user/advanced-chat/knowledge-bases", { method: "POST", body: { name: name.trim(), description: description.trim() } }); setModal(""); setName(""); setDescription(""); await loadBases() } catch (e) { setError(message(e)) } }
  const removeBase = (base: KnowledgeBase) => Alert.alert("删除知识库", `确定删除“${base.name}”及其中的全部文档？`, [{ text: "取消", style: "cancel" }, { text: "删除", style: "destructive", onPress: async () => { try { await request(`/user/advanced-chat/knowledge-bases/${encodeURIComponent(base.id)}`, { method: "DELETE" }); if (selected?.id === base.id) setSelected(null); await loadBases() } catch (e) { setError(message(e)) } } }])
  const createDocument = async () => { if (!selected || !name.trim()) { setError("请输入文档名称"); return } try { const data = await request<any>(`/user/advanced-chat/knowledge-bases/${encodeURIComponent(selected.id)}/documents/text`, { method: "POST", body: { name: name.trim(), content: "# 新文档\n\n" } }); setModal(""); setName(""); await loadDocuments(selected); const document = data?.document; if (document?.id) { setEditing(document); setContent("# 新文档\n\n") } } catch (e) { setError(message(e)) } }
  const openDocument = async (document: KnowledgeDocument) => { if (!selected || !document.editable) return; try { const data = await request<any>(`/user/advanced-chat/knowledge-bases/${encodeURIComponent(selected.id)}/documents/${encodeURIComponent(document.id)}/content`); setEditing(data?.document || document); setContent(typeof data?.content === "string" ? data.content : "") } catch (e) { setError(message(e)) } }
  const saveDocument = async () => { if (!selected || !editing) return; try { await request(`/user/advanced-chat/knowledge-bases/${encodeURIComponent(selected.id)}/documents/${encodeURIComponent(editing.id)}/content`, { method: "PUT", body: { name: editing.name, content } }); await loadDocuments(selected); setEditing(null); setContent("") } catch (e) { setError(message(e)) } }
  const removeDocument = (document: KnowledgeDocument) => { if (!selected) return; Alert.alert("删除文档", `确定删除“${document.name}”？`, [{ text: "取消", style: "cancel" }, { text: "删除", style: "destructive", onPress: async () => { try { await request(`/user/advanced-chat/knowledge-bases/${encodeURIComponent(selected.id)}/documents/${encodeURIComponent(document.id)}`, { method: "DELETE" }); await loadDocuments(selected) } catch (e) { setError(message(e)) } } }]) }
  if (editing && selected) return <View style={styles.root}><Top colors={colors} title={editing.name} onBack={() => { setEditing(null); setContent("") }} right="" /><Text style={{ color: colors.muted, paddingHorizontal: 14, paddingTop: 8 }}>{selected.name}</Text><Input colors={colors} label="内容" value={content} onChangeText={setContent} multiline style={styles.editor} /><View style={styles.actions}><Action colors={colors} title="保存文档" onPress={saveDocument} /></View></View>
  if (selected) return <View style={styles.root}><Top colors={colors} title={selected.name} onBack={() => setSelected(null)} right="add" onRight={() => { setName(""); setModal("document") }} />{error ? <Text style={{ color: colors.destructive, padding: 12 }}>{error}</Text> : null}<FlatList data={documents} keyExtractor={item => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={{ color: colors.muted }}>暂无知识库文档</Text>} renderItem={({ item }) => <Pressable onPress={() => openDocument(item)} onLongPress={() => removeDocument(item)} style={[styles.row, { borderColor: colors.border, backgroundColor: colors.card, opacity: item.editable ? 1 : .72 }]}><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontWeight: "600" }}>{item.name}</Text><Text style={{ color: colors.muted, fontSize: 12 }}>{item.editable ? "可在线编辑" : "仅可下载"} · {item.embedding_status || "pending"}</Text></View><Text style={{ color: colors.muted }}>›</Text></Pressable>} /><Modal visible={modal === "document"} transparent animationType="slide"><Sheet colors={colors} title="新建文档" onClose={() => setModal("")}><ScrollView contentContainerStyle={styles.form}><Input colors={colors} label="文档名称" value={name} onChangeText={setName} /><Action colors={colors} title="创建并编辑" onPress={createDocument} /></ScrollView></Sheet></Modal></View>
  return <View style={styles.root}><Top colors={colors} title="知识库" onBack={onBack} right="add" onRight={() => { setName(""); setDescription(""); setModal("base") }} />{error ? <Text style={{ color: colors.destructive, padding: 12 }}>{error}</Text> : null}<FlatList data={bases} keyExtractor={item => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={{ color: colors.muted }}>暂无知识库</Text>} renderItem={({ item }) => <Pressable onPress={() => openBase(item)} onLongPress={() => removeBase(item)} style={[styles.row, { borderColor: colors.border, backgroundColor: colors.card }]}><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontWeight: "600" }}>{item.name}</Text><Text style={{ color: colors.muted, fontSize: 12 }} numberOfLines={1}>{item.description || "未填写描述"}</Text></View><Text style={{ color: colors.muted, fontSize: 12 }}>{item.document_count || 0} 份</Text><Text style={{ color: colors.muted }}>›</Text></Pressable>} /><Modal visible={modal === "base"} transparent animationType="slide"><Sheet colors={colors} title="新建知识库" onClose={() => setModal("")}><ScrollView contentContainerStyle={styles.form}><Input colors={colors} label="知识库名称" value={name} onChangeText={setName} /><Input colors={colors} label="描述" value={description} onChangeText={setDescription} multiline /><Action colors={colors} title="创建知识库" onPress={saveBase} /></ScrollView></Sheet></Modal></View>
}

function message(error: unknown) { return error instanceof Error ? error.message : "发生未知错误" }
const styles = StyleSheet.create({ root: { flex: 1 }, list: { padding: 16, gap: 10 }, row: { minHeight: 64, borderWidth: 1, borderRadius: 12, padding: 12, flexDirection: "row", alignItems: "center", gap: 10 }, form: { gap: 14, paddingBottom: 18 }, editor: { minHeight: 350, margin: 14 }, actions: { padding: 14 } })
