import { Ionicons } from "@expo/vector-icons"
import * as DocumentPicker from "expo-document-picker"
import { useCallback, useEffect, useState } from "react"
import { Alert, FlatList, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native"
import { request, uploadFile } from "../api"
import type { Palette } from "../theme"
import MemoriesPage from "./MemoriesPage"
import TasksPage from "./TasksPage"
import WorkspacesPage from "./WorkspacesPage"

type LibraryKind = "files" | "devices" | "workspaces" | "deliveries" | "tasks" | "memories"
const config: Record<LibraryKind, { label: string; endpoint: string; icon: keyof typeof Ionicons.glyphMap }> = { files: { label: "文件库", endpoint: "/user/advanced-chat/files", icon: "document-text-outline" }, devices: { label: "设备", endpoint: "/user/advanced-chat/devices", icon: "laptop-outline" }, workspaces: { label: "工作区", endpoint: "/user/advanced-chat/workspaces", icon: "folder-open-outline" }, deliveries: { label: "结果投递", endpoint: "/user/advanced-chat/deliveries", icon: "send-outline" }, tasks: { label: "定时任务", endpoint: "/user/advanced-chat/scheduled-tasks", icon: "calendar-outline" }, memories: { label: "记忆", endpoint: "/user/advanced-chat/memories", icon: "bulb-outline" } }

export default function LibraryPage({ colors }: { colors: Palette }) {
  const [kind, setKind] = useState<LibraryKind>("files"); const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [uploading, setUploading] = useState(false); const [detail, setDetail] = useState<"tasks" | "memories" | "workspaces" | "">("")
  const load = useCallback(async () => { setLoading(true); try { const data = await request<any>(config[kind].endpoint); const next = data?.files || data?.devices || data?.workspaces || data?.deliveries || data?.tasks || data?.memories || data; setItems(Array.isArray(next) ? next : []) } catch (e) { setError(message(e)); setItems([]) } finally { setLoading(false) } }, [kind])
  useEffect(() => { void load() }, [load])
  const upload = async () => { if (kind !== "files" || uploading) return; const picked = await DocumentPicker.getDocumentAsync({ multiple: true, copyToCacheDirectory: false }); if (picked.canceled) return; setUploading(true); try { for (const asset of picked.assets) await uploadFile("/user/advanced-chat/files", asset); await load() } catch (e) { setError(message(e)) } finally { setUploading(false) } }
  const remove = (item: any) => Alert.alert("删除文件", `确定删除“${item.name || "文件"}”？`, [{ text: "取消", style: "cancel" }, { text: "删除", style: "destructive", onPress: async () => { try { await request(`/user/advanced-chat/files/${encodeURIComponent(item.id)}`, { method: "DELETE" }); await load() } catch (e) { setError(message(e)) } } }])
  if (detail === "tasks") return <TasksPage colors={colors} onBack={() => setDetail("")} />
  if (detail === "memories") return <MemoriesPage colors={colors} onBack={() => setDetail("")} />
  if (detail === "workspaces") return <WorkspacesPage colors={colors} onBack={() => setDetail("")} />
  return <View style={styles.flex}><View style={[styles.header, { borderColor: colors.border }]}><Text style={[styles.title, { color: colors.text }]}>资源</Text>{kind === "files" ? <Pressable onPress={upload}><Ionicons name="cloud-upload-outline" size={22} color={colors.text} /></Pressable> : null}</View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.pills}>{(Object.keys(config) as LibraryKind[]).map(key => <Pressable key={key} onPress={() => { setKind(key); if (key === "tasks") setDetail("tasks"); if (key === "memories") setDetail("memories"); if (key === "workspaces") setDetail("workspaces") }} style={[styles.pill, { backgroundColor: key === kind ? colors.primary : colors.input }]}><Text style={{ color: key === kind ? colors.primaryText : colors.text }}>{config[key].label}</Text></Pressable>)}</ScrollView><FlatList style={styles.flex} contentContainerStyle={styles.list} data={items} keyExtractor={(item, index) => String(item.id || item.name || index)} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} />} ListHeaderComponent={<><Text style={[styles.pageTitle, { color: colors.text }]}>{config[kind].label}</Text><Text style={[styles.muted, { color: colors.muted }]}>{items.length} 项{uploading ? " · 上传中" : ""}</Text></>} ListEmptyComponent={loading ? <Text style={{ color: colors.muted }}>加载中…</Text> : <Text style={{ color: colors.muted, paddingVertical: 30 }}>暂无{config[kind].label}</Text>} renderItem={({ item }) => <Pressable onLongPress={kind === "files" ? () => remove(item) : undefined} style={[styles.row, { backgroundColor: colors.card, borderColor: colors.border }]}><Ionicons name={config[kind].icon} size={22} color={colors.text} /><View style={styles.rowText}><Text style={[styles.name, { color: colors.text }]} numberOfLines={1}>{item.name || item.title || item.hostname || item.id || "未命名"}</Text><Text style={[styles.muted, { color: colors.muted }]} numberOfLines={2}>{String(item.description || item.type || item.status || item.path || "")}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted} /></Pressable>} /></View>
}
function message(error: unknown) { return error instanceof Error ? error.message : "发生未知错误" }
const styles = StyleSheet.create({ flex: { flex: 1 }, header: { height: 58, borderBottomWidth: StyleSheet.hairlineWidth, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, title: { fontSize: 18, fontWeight: "600" }, pills: { padding: 10, gap: 8 }, pill: { paddingHorizontal: 14, height: 34, borderRadius: 17, justifyContent: "center" }, list: { padding: 16, gap: 10, paddingBottom: 24, flexGrow: 1 }, pageTitle: { fontSize: 24, fontWeight: "700" }, muted: { fontSize: 12 }, row: { minHeight: 70, borderWidth: 1, borderRadius: 14, padding: 12, flexDirection: "row", alignItems: "center", gap: 12 }, rowText: { flex: 1 }, name: { fontSize: 15, fontWeight: "600" } })
