import { Ionicons } from "@expo/vector-icons"
import { useState } from "react"
import { KeyboardAvoidingView, Modal, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native"
import { configureServer, DEFAULT_SERVER, getServerURL, login } from "../api"
import type { Palette } from "../theme"

export default function LoginPage({ colors, onLoggedIn }: { colors: Palette; onLoggedIn: () => void }) {
  const [identifier, setIdentifier] = useState(""); const [password, setPassword] = useState(""); const [server, setServer] = useState(getServerURL()); const [busy, setBusy] = useState(false); const [showServer, setShowServer] = useState(false); const [error, setError] = useState("")
  const submit = async () => { setBusy(true); setError(""); try { await login(identifier.trim(), password); onLoggedIn() } catch (e) { setError(e instanceof Error ? e.message : "登录失败") } finally { setBusy(false) } }
  const saveServer = async () => { try { await configureServer(server); setShowServer(false) } catch (e) { setError(e instanceof Error ? e.message : "服务地址无效") } }
  return <View style={styles.root}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.center}><View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.logo, { backgroundColor: colors.primary }]}><Ionicons name="sparkles" size={28} color={colors.primaryText} /></View><Text style={[styles.brand, { color: colors.text }]}>Veloce</Text><Text style={[styles.subtitle, { color: colors.muted }]}>你的 AI 工作台</Text><Input colors={colors} placeholder="用户名或邮箱" value={identifier} onChangeText={setIdentifier} autoCapitalize="none" /><Input colors={colors} placeholder="密码" value={password} onChangeText={setPassword} secureTextEntry onSubmitEditing={submit} />{error ? <Text style={{ color: colors.destructive }}>{error}</Text> : null}<Action colors={colors} title={busy ? "登录中…" : "登录"} onPress={submit} disabled={busy || !identifier.trim() || !password} /><Pressable onPress={() => setShowServer(true)}><Text style={{ color: colors.muted, fontSize: 12 }}>服务地址：{getServerURL()}</Text></Pressable><Text style={[styles.note, { color: colors.muted }]}>OAuth、通行密钥和验证码登录请使用 Web 端。</Text></View></KeyboardAvoidingView><Modal visible={showServer} transparent animationType="fade"><View style={styles.modal}><Pressable style={StyleSheet.absoluteFill} onPress={() => setShowServer(false)} /><View style={[styles.sheet, { backgroundColor: colors.card }]}><Text style={[styles.sheetTitle, { color: colors.text }]}>服务器连接</Text><Text style={{ color: colors.muted }}>实体设备请使用局域网 IP。</Text><Input colors={colors} value={server} onChangeText={setServer} placeholder={DEFAULT_SERVER} autoCapitalize="none" /><Action colors={colors} title="保存地址" onPress={saveServer} /></View></View></Modal></View>
}
function Input({ colors, ...props }: any) { return <TextInput {...props} placeholderTextColor={colors.muted} style={[styles.input, { color: colors.text, backgroundColor: colors.input, borderColor: colors.border }]} /> }
function Action({ colors, title, onPress, disabled }: any) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.action, { backgroundColor: colors.primary, opacity: disabled ? .45 : 1 }]}><Text style={{ color: colors.primaryText, fontWeight: "600" }}>{title}</Text></Pressable> }
const styles = StyleSheet.create({ root: { flex: 1 }, center: { flex: 1, justifyContent: "center", padding: 24 }, card: { borderWidth: 1, borderRadius: 20, padding: 24, gap: 14, maxWidth: 440, width: "100%", alignSelf: "center" }, logo: { height: 60, width: 60, borderRadius: 18, alignItems: "center", justifyContent: "center", alignSelf: "center" }, brand: { fontSize: 30, fontWeight: "700", textAlign: "center" }, subtitle: { fontSize: 14, textAlign: "center", marginBottom: 8 }, input: { minHeight: 48, borderWidth: 1, borderRadius: 12, fontSize: 16, paddingHorizontal: 14 }, action: { height: 48, borderRadius: 12, alignItems: "center", justifyContent: "center" }, note: { fontSize: 12, lineHeight: 18, textAlign: "center" }, modal: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,.36)" }, sheet: { padding: 24, gap: 14, borderTopLeftRadius: 24, borderTopRightRadius: 24 }, sheetTitle: { fontSize: 20, fontWeight: "700" } })
