import { useCallback, useEffect, useState } from "react"
import { Alert, FlatList, Modal, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native"
import { request } from "../api"
import type { Palette } from "../theme"
import { Action, Input, Sheet, Top, Toggle } from "./TasksPage"

type Memory = Record<string, any>
const kinds = ["facts", "preferences", "projects", "instructions", "notes"]
export default function MemoriesPage({ colors, onBack }: { colors: Palette; onBack: () => void }) {
  const [items, setItems] = useState<Memory[]>([]); const [agents, setAgents] = useState<any[]>([]); const [editor, setEditor] = useState<Memory | null>(null); const [form, setForm] = useState<any>({ scope: "global", agent_id: "", kind: "facts", title: "", content: "", enabled: true }); const [error, setError] = useState("")
  const load = useCallback(async () => { try { const [data, nextAgents] = await Promise.all([request<any>("/user/advanced-chat/memories"), request<any[]>("/user/advanced-chat/agents")]); setItems(Array.isArray(data?.memories) ? data.memories : Array.isArray(data) ? data : []); setAgents(Array.isArray(nextAgents) ? nextAgents : []) } catch (e) { setError(message(e)) } }, [])
  useEffect(() => { void load() }, [load])
  const open = (item?: Memory) => { setEditor(item || {}); setForm(item ? { scope: item.scope || "global", agent_id: item.agent_id || "", kind: item.kind || "facts", title: item.title || "", content: item.content || "", enabled: item.enabled !== false, id: item.id } : { scope: "global", agent_id: "", kind: "facts", title: "", content: "", enabled: true }) }
  const save = async () => { if (!form.content.trim() || (form.scope === "agent" && !form.agent_id)) { setError("请填写内容，并选择代理范围"); return } try { const payload = { scope: form.scope, agent_id: form.scope === "agent" ? form.agent_id : "", kind: form.kind, title: form.title.trim(), content: form.content, enabled: form.enabled }; await request(form.id ? `/user/advanced-chat/memories/${encodeURIComponent(form.id)}` : "/user/advanced-chat/memories", { method: form.id ? "PUT" : "POST", body: payload }); setEditor(null); await load() } catch (e) { setError(message(e)) } }
  const remove = (item: Memory) => Alert.alert("删除记忆", `确定删除“${item.title || item.kind}”？`, [{ text: "取消", style: "cancel" }, { text: "删除", style: "destructive", onPress: async () => { try { await request(`/user/advanced-chat/memories/${encodeURIComponent(item.id)}`, { method: "DELETE" }); await load() } catch (e) { setError(message(e)) } } }])
  return <View style={styles.root}><Top colors={colors} title="记忆" onBack={onBack} right="add" onRight={() => open()} />{error ? <Text style={{ color: colors.destructive, padding: 12 }}>{error}</Text> : null}<FlatList data={items} keyExtractor={item => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={{ color: colors.muted }}>暂无记忆</Text>} renderItem={({ item }) => <Pressable onPress={() => open(item)} onLongPress={() => remove(item)} style={[styles.row, { borderColor: colors.border, backgroundColor: colors.card }]}><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontWeight: "600" }}>{item.title || item.kind || "未命名记忆"}</Text><Text style={{ color: colors.muted, fontSize: 12 }}>{item.scope === "agent" ? `代理：${item.agent_id}` : "全局"} · {item.enabled === false ? "已停用" : "已启用"}</Text><Text style={{ color: colors.muted, fontSize: 12 }} numberOfLines={2}>{item.content}</Text></View><Text style={{ color: colors.muted }}>编辑</Text></Pressable>} /><Modal visible={Boolean(editor)} transparent animationType="slide"><Sheet colors={colors} title={editor?.id ? "编辑记忆" : "新建记忆"} onClose={() => setEditor(null)}><ScrollView contentContainerStyle={styles.form}><Input colors={colors} label="标题" value={form.title} onChangeText={(v: string) => setForm({ ...form, title: v })} /><Choice colors={colors} label="类型" values={kinds} value={form.kind} onChange={(v: string) => setForm({ ...form, kind: v })} /><Choice colors={colors} label="范围" values={["global", "agent"]} labels={["全局", "代理"]} value={form.scope} onChange={(v: string) => setForm({ ...form, scope: v })} />{form.scope === "agent" ? <Choice colors={colors} label="代理" values={agents.map(item => item.id)} labels={agents.map(item => item.name)} value={form.agent_id} onChange={(v: string) => setForm({ ...form, agent_id: v })} /> : null}<Input colors={colors} label="内容" value={form.content} onChangeText={(v: string) => setForm({ ...form, content: v })} multiline /><Toggle colors={colors} label="启用" value={form.enabled} onChange={(v: boolean) => setForm({ ...form, enabled: v })} /><Action colors={colors} title="保存记忆" onPress={save} /></ScrollView></Sheet></Modal></View>
}
function Choice({ colors, label, values, labels, value, onChange }: any) { return <View style={styles.field}><Text style={{ color: colors.muted, fontSize: 12 }}>{label}</Text><ScrollView horizontal contentContainerStyle={styles.choices}>{values.map((item: string, index: number) => <Pressable key={`${item}-${index}`} onPress={() => onChange(item)} style={[styles.choice, { backgroundColor: value === item ? colors.primary : colors.input }]}><Text style={{ color: value === item ? colors.primaryText : colors.text }}>{labels?.[index] || item}</Text></Pressable>)}</ScrollView></View> }
function message(error: unknown) { return error instanceof Error ? error.message : "发生未知错误" }
const styles = StyleSheet.create({ root: { flex: 1 }, list: { paddingVertical: 0 }, row: { minHeight: 70, borderBottomWidth: StyleSheet.hairlineWidth, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", gap: 12 }, form: { gap: 14, paddingBottom: 18 }, field: { gap: 5 }, choices: { gap: 8 }, choice: { height: 36, borderRadius: 18, paddingHorizontal: 13, justifyContent: "center" } })
