import { Ionicons } from "@expo/vector-icons"
import { useEffect, useState } from "react"
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native"
import { configureServer, getServerURL, request } from "../api"
import type { Palette } from "../theme"
import type { ThemeMode, User } from "../types"

type Preferences = { theme: ThemeMode; language: "zh" | "en" }
export default function SettingsPage({ colors, preferences, savePreferences, onLogout }: { colors: Palette; preferences: Preferences; savePreferences: (p: Preferences) => void; onLogout: () => void }) {
  const [user, setUser] = useState<User | null>(null); const [serverOpen, setServerOpen] = useState(false); const [server, setServer] = useState(getServerURL()); const [notice, setNotice] = useState("")
  useEffect(() => { request<User>("/user/me").then(setUser).catch(e => setNotice(e instanceof Error ? e.message : "加载账户失败")) }, [])
  const saveServer = async () => { try { await configureServer(server); setServerOpen(false); setNotice("服务地址已保存，重新登录后生效") } catch (e) { setNotice(e instanceof Error ? e.message : "保存失败") } }
  return <><ScrollView contentContainerStyle={styles.content}><Text style={[styles.title, { color: colors.text }]}>设置</Text><Section colors={colors} title="账户"><Row colors={colors} icon="person-circle-outline" label={user?.username || user?.email || "账户信息加载中"} detail={user?.email} /><Row colors={colors} icon="server-outline" label="服务器连接" detail={getServerURL()} onPress={() => setServerOpen(true)} /></Section><Section colors={colors} title="外观"><View style={styles.choices}>{(["light", "dark", "system"] as ThemeMode[]).map(mode => <Pressable key={mode} onPress={() => savePreferences({ ...preferences, theme: mode })} style={[styles.choice, { borderColor: preferences.theme === mode ? colors.primary : colors.border, backgroundColor: preferences.theme === mode ? colors.input : colors.card }]}><Text style={{ color: colors.text }}>{mode === "light" ? "浅色" : mode === "dark" ? "深色" : "跟随系统"}</Text></Pressable>)}</View><Row colors={colors} icon="language-outline" label="语言" detail={preferences.language === "zh" ? "简体中文" : "English"} right={<Switch value={preferences.language === "en"} onValueChange={v => savePreferences({ ...preferences, language: v ? "en" : "zh" })} trackColor={{ false: colors.border, true: colors.primary }} />} /></Section><Section colors={colors} title="关于"><Row colors={colors} icon="information-circle-outline" label="Veloce Mobile" detail="React Native / Expo" /><Row colors={colors} icon="desktop-outline" label="桌面专属能力" detail="终端、通行密钥与 OAuth 请在 Web/桌面端使用" /></Section>{notice ? <Text style={{ color: colors.destructive }}>{notice}</Text> : null}<Pressable onPress={() => Alert.alert("退出登录", "是否清除此设备上的登录凭据？", [{ text: "取消", style: "cancel" }, { text: "退出", style: "destructive", onPress: onLogout }])} style={[styles.logout, { backgroundColor: colors.destructive }]}><Text style={{ color: "#fff", fontWeight: "600" }}>退出登录</Text></Pressable></ScrollView><Modal visible={serverOpen} transparent animationType="slide"><View style={styles.modal}><Pressable style={StyleSheet.absoluteFill} onPress={() => setServerOpen(false)} /><View style={[styles.sheet, { backgroundColor: colors.card }]}><Text style={[styles.sheetTitle, { color: colors.text }]}>服务器连接</Text><TextInput value={server} onChangeText={setServer} autoCapitalize="none" style={[styles.input, { color: colors.text, backgroundColor: colors.input, borderColor: colors.border }]} /><Pressable onPress={saveServer} style={[styles.save, { backgroundColor: colors.primary }]}><Text style={{ color: colors.primaryText, fontWeight: "600" }}>保存</Text></Pressable></View></View></Modal></>
}
function Section({ colors, title, children }: any) { return <View><Text style={[styles.sectionTitle, { color: colors.muted }]}>{title}</Text><View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>{children}</View></View> }
function Row({ colors, icon, label, detail, onPress, right }: any) { return <Pressable disabled={!onPress} onPress={onPress} style={styles.row}><Ionicons name={icon} size={21} color={colors.text} /><View style={{ flex: 1 }}><Text style={[styles.label, { color: colors.text }]}>{label}</Text>{detail ? <Text style={[styles.detail, { color: colors.muted }]} numberOfLines={1}>{detail}</Text> : null}</View>{right || (onPress ? <Ionicons name="chevron-forward" size={18} color={colors.muted} /> : null)}</Pressable> }
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 105, gap: 20 }, title: { fontSize: 26, fontWeight: "700" }, sectionTitle: { fontSize: 12, fontWeight: "600", marginBottom: 7, textTransform: "uppercase" }, card: { borderWidth: 1, borderRadius: 14, overflow: "hidden" }, row: { minHeight: 64, paddingHorizontal: 14, alignItems: "center", flexDirection: "row", gap: 12 }, label: { fontSize: 15, fontWeight: "500" }, detail: { fontSize: 12, marginTop: 3 }, choices: { flexDirection: "row", gap: 8, marginBottom: 10 }, choice: { flex: 1, height: 56, borderWidth: 1, borderRadius: 12, alignItems: "center", justifyContent: "center" }, logout: { height: 48, borderRadius: 12, alignItems: "center", justifyContent: "center" }, modal: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,.36)" }, sheet: { padding: 24, gap: 14, borderTopLeftRadius: 24, borderTopRightRadius: 24 }, sheetTitle: { fontSize: 20, fontWeight: "700" }, input: { height: 48, borderWidth: 1, borderRadius: 10, paddingHorizontal: 12 }, save: { height: 46, borderRadius: 10, alignItems: "center", justifyContent: "center" } })
