import { Ionicons } from "@expo/vector-icons"
import { useCallback, useEffect, useState } from "react"
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native"
import { configureServer, getServerURL, request } from "../api"
import type { Palette } from "../theme"
import type { ThemeMode, User } from "../types"
import { Action, Choice, Input, Sheet } from "./TasksPage"

type Preferences = { theme: ThemeMode; language: "zh" | "en" }
type AdvancedSettings = { title_model_name?: string; title_user_channel_id?: number; title_generation_scope?: "all" | "recent"; connector_approval_agent_id?: string }
type PasswordMethod = { method?: "email_code" | "current_password"; email?: string; password_set?: boolean }

export default function SettingsPage({ colors, preferences, savePreferences, onLogout }: { colors: Palette; preferences: Preferences; savePreferences: (p: Preferences) => void; onLogout: () => void }) {
  const [user, setUser] = useState<User | null>(null)
  const [serverOpen, setServerOpen] = useState(false)
  const [profileOpen, setProfileOpen] = useState(false)
  const [assistantOpen, setAssistantOpen] = useState(false)
  const [securityOpen, setSecurityOpen] = useState(false)
  const [server, setServer] = useState(getServerURL())
  const [catalog, setCatalog] = useState<any[]>([])
  const [agents, setAgents] = useState<any[]>([])
  const [assistantSettings, setAssistantSettings] = useState<AdvancedSettings>({ title_model_name: "", title_user_channel_id: 0, title_generation_scope: "recent", connector_approval_agent_id: "" })
  const [passwordMethod, setPasswordMethod] = useState<PasswordMethod>({})
  const [currentPassword, setCurrentPassword] = useState("")
  const [newPassword, setNewPassword] = useState("")
  const [confirmPassword, setConfirmPassword] = useState("")
  const [emailCode, setEmailCode] = useState("")
  const [notice, setNotice] = useState("")
  const [saving, setSaving] = useState(false)
  const [checking, setChecking] = useState(false)

  const load = useCallback(async () => {
    try {
      const [nextUser, settings, nextCatalog, nextAgents, nextPasswordMethod] = await Promise.all([
        request<User>("/user/me"),
        request<AdvancedSettings>("/user/advanced-chat/settings"),
        request<any[]>("/user/catalog"),
        request<any[]>("/user/advanced-chat/agents"),
        request<PasswordMethod>("/user/password/method").catch(() => ({})),
      ])
      setUser(nextUser)
      setAssistantSettings({ title_model_name: settings?.title_model_name || "", title_user_channel_id: Number(settings?.title_user_channel_id || 0), title_generation_scope: settings?.title_generation_scope === "all" ? "all" : "recent", connector_approval_agent_id: settings?.connector_approval_agent_id || "" })
      setCatalog(Array.isArray(nextCatalog) ? nextCatalog : [])
      setAgents(Array.isArray(nextAgents) ? nextAgents : [])
      setPasswordMethod(nextPasswordMethod || {})
    } catch (cause) { setNotice(message(cause)) }
  }, [])
  useEffect(() => { void load() }, [load])

  const models = assistantSettings.title_user_channel_id ? catalog.find(item => Number(item.id) === assistantSettings.title_user_channel_id)?.models || [] : [...new Set(catalog.flatMap(item => item.models || []))]
  const saveServer = async () => { try { await configureServer(server); setServerOpen(false); setNotice("服务地址已保存，重新登录后生效") } catch (cause) { setNotice(message(cause)) } }
  const saveAssistant = async () => { setSaving(true); try { const saved = await request<AdvancedSettings>("/user/advanced-chat/settings", { method: "PUT", body: { title_model_name: assistantSettings.title_model_name || "", title_user_channel_id: Number(assistantSettings.title_user_channel_id) || 0, title_generation_scope: assistantSettings.title_generation_scope || "recent", connector_approval_agent_id: assistantSettings.connector_approval_agent_id || "" } }); setAssistantSettings(current => ({ ...current, ...saved })); setAssistantOpen(false); setNotice("助手设置已保存") } catch (cause) { setNotice(message(cause)) } finally { setSaving(false) } }
  const testConnection = async () => { setChecking(true); try { const current = await request<User>("/user/me"); setUser(current); setNotice("服务器连接正常") } catch (cause) { setNotice(message(cause)) } finally { setChecking(false) } }
  const sendPasswordCode = async () => { try { await request("/user/password/email-code", { method: "POST" }); setNotice("验证码已发送") } catch (cause) { setNotice(message(cause)) } }
  const changePassword = async () => { if (newPassword.length < 8) { setNotice("新密码至少需要 8 位"); return } if (newPassword !== confirmPassword) { setNotice("两次输入的新密码不一致"); return } try { await request("/user/password/change", { method: "POST", body: { current_password: currentPassword, new_password: newPassword, email_code: emailCode } }); setCurrentPassword(""); setNewPassword(""); setConfirmPassword(""); setEmailCode(""); setSecurityOpen(false); setNotice("密码已更新") } catch (cause) { setNotice(message(cause)) } }

  return <><ScrollView contentContainerStyle={styles.content}><View style={styles.pageHeader}><View><Text style={[styles.title, { color: colors.text }]}>设置</Text><Text style={{ color: colors.muted, fontSize: 12 }}>账户、助手和应用偏好</Text></View><Pressable onPress={() => void load()} style={({ pressed }) => pressed && styles.pressed}><Ionicons name="refresh-outline" size={22} color={colors.text} /></Pressable></View><Section colors={colors} title="账户"><Row colors={colors} icon="person-circle-outline" label={user?.username || user?.email || "账户信息"} detail={user?.email || "加载中…"} onPress={() => setProfileOpen(true)} /><Row colors={colors} icon="lock-closed-outline" label="账户安全" detail={passwordMethod.method === "email_code" ? "使用邮箱验证码修改密码" : "修改登录密码"} onPress={() => setSecurityOpen(true)} /></Section><Section colors={colors} title="助手"><Row colors={colors} icon="chatbubble-ellipses-outline" label="会话标题与审批" detail={assistantSettings.title_model_name ? `标题模型：${assistantSettings.title_model_name}` : "使用本地标题摘要"} onPress={() => setAssistantOpen(true)} /></Section><Section colors={colors} title="外观"><View style={styles.choices}>{(["light", "dark", "system"] as ThemeMode[]).map(mode => <Pressable key={mode} onPress={() => savePreferences({ ...preferences, theme: mode })} style={[styles.choice, { borderColor: preferences.theme === mode ? colors.primary : colors.border, backgroundColor: preferences.theme === mode ? colors.input : colors.card }]}><Ionicons name={mode === "light" ? "sunny-outline" : mode === "dark" ? "moon-outline" : "phone-portrait-outline"} size={19} color={colors.text} /><Text style={{ color: colors.text }}>{mode === "light" ? "浅色" : mode === "dark" ? "深色" : "系统"}</Text></Pressable>)}</View><Row colors={colors} icon="language-outline" label="语言" detail={preferences.language === "zh" ? "简体中文" : "English"} right={<Switch value={preferences.language === "en"} onValueChange={value => savePreferences({ ...preferences, language: value ? "en" : "zh" })} trackColor={{ false: colors.border, true: colors.primary }} />} /></Section><Section colors={colors} title="应用"><Row colors={colors} icon="server-outline" label="服务器连接" detail={getServerURL()} onPress={() => setServerOpen(true)} /><Row colors={colors} icon="pulse-outline" label={checking ? "正在检查连接…" : "检查服务器状态"} detail="验证账户 API 是否可访问" onPress={() => void testConnection()} /><Row colors={colors} icon="information-circle-outline" label="Veloce Mobile" detail="React Native / Expo · 移动端控制台" /></Section>{notice ? <Text style={{ color: colors.destructive, fontSize: 13 }}>{notice}</Text> : null}<Pressable onPress={() => Alert.alert("退出登录", "是否清除此设备上的登录凭据？", [{ text: "取消", style: "cancel" }, { text: "退出", style: "destructive", onPress: onLogout }])} style={[styles.logout, { backgroundColor: colors.destructive }]}><Ionicons name="log-out-outline" size={19} color="#fff" /><Text style={{ color: "#fff", fontWeight: "600" }}>退出登录</Text></Pressable></ScrollView>
    <Modal visible={profileOpen} transparent animationType="slide" onRequestClose={() => setProfileOpen(false)}><Sheet colors={colors} title="账户资料" onClose={() => setProfileOpen(false)}><View style={styles.sheetContent}><ProfileField colors={colors} label="用户名" value={user?.username || "-"} /><ProfileField colors={colors} label="邮箱" value={user?.email || "-"} /><ProfileField colors={colors} label="角色" value={user?.is_admin ? "管理员" : "普通用户"} /><ProfileField colors={colors} label="头像地址" value={user?.avatar_url || "未设置"} /></View></Sheet></Modal>
    <Modal visible={serverOpen} transparent animationType="slide" onRequestClose={() => setServerOpen(false)}><Sheet colors={colors} title="服务器连接" onClose={() => setServerOpen(false)}><View style={styles.sheetContent}><Input colors={colors} label="服务器地址" value={server} autoCapitalize="none" autoCorrect={false} keyboardType="url" onChangeText={setServer} /><Text style={{ color: colors.muted, fontSize: 12 }}>更换地址后需要重新登录。</Text><Action colors={colors} title="保存服务器地址" onPress={saveServer} /></View></Sheet></Modal>
    <Modal visible={assistantOpen} transparent animationType="slide" onRequestClose={() => setAssistantOpen(false)}><Sheet colors={colors} title="助手设置" onClose={() => setAssistantOpen(false)}><ScrollView contentContainerStyle={styles.sheetContent}><Text style={{ color: colors.muted, fontSize: 12 }}>发送第一条消息后，系统可使用下列模型生成更精确的会话标题。</Text><Choice colors={colors} label="标题生成渠道" values={["0", ...catalog.map(item => String(item.id))]} labels={["任意可用渠道", ...catalog.map(item => item.name)]} value={String(assistantSettings.title_user_channel_id || 0)} onChange={(value: string) => setAssistantSettings(current => ({ ...current, title_user_channel_id: Number(value) || 0, title_model_name: "" }))} /><Choice colors={colors} label="标题生成模型" values={["", ...models]} labels={["不使用模型生成标题", ...models]} value={assistantSettings.title_model_name || ""} onChange={(value: string) => setAssistantSettings(current => ({ ...current, title_model_name: value }))} /><Choice colors={colors} label="重新生成标题范围" values={["recent", "all"]} labels={["最近对话", "全部对话"]} value={assistantSettings.title_generation_scope || "recent"} onChange={(value: "recent" | "all") => setAssistantSettings(current => ({ ...current, title_generation_scope: value }))} /><Choice colors={colors} label="连接器审批助手" values={["", ...agents.map(item => item.id)]} labels={["暂不使用助手审批", ...agents.map(item => item.name)]} value={assistantSettings.connector_approval_agent_id || ""} onChange={(value: string) => setAssistantSettings(current => ({ ...current, connector_approval_agent_id: value }))} /><Action colors={colors} title={saving ? "保存中…" : "保存助手设置"} onPress={saveAssistant} disabled={saving} /></ScrollView></Sheet></Modal>
    <Modal visible={securityOpen} transparent animationType="slide" onRequestClose={() => setSecurityOpen(false)}><Sheet colors={colors} title="账户安全" onClose={() => setSecurityOpen(false)}><ScrollView contentContainerStyle={styles.sheetContent}>{passwordMethod.method === "email_code" ? <><Text style={{ color: colors.muted, fontSize: 12 }}>账户将通过邮箱验证码验证本次密码修改。</Text><Pressable onPress={sendPasswordCode} style={[styles.codeButton, { backgroundColor: colors.input }]}><Text style={{ color: colors.text }}>发送验证码至 {passwordMethod.email || "绑定邮箱"}</Text></Pressable><Input colors={colors} label="邮箱验证码" value={emailCode} keyboardType="numeric" onChangeText={setEmailCode} /></> : <Input colors={colors} label="当前密码" value={currentPassword} secureTextEntry onChangeText={setCurrentPassword} />}<Input colors={colors} label="新密码" value={newPassword} secureTextEntry onChangeText={setNewPassword} /><Input colors={colors} label="确认新密码" value={confirmPassword} secureTextEntry onChangeText={setConfirmPassword} /><Action colors={colors} title="保存新密码" onPress={changePassword} /></ScrollView></Sheet></Modal>
  </>}

function Section({ colors, title, children }: any) { return <View style={styles.section}><Text style={[styles.sectionTitle, { color: colors.muted }]}>{title}</Text><View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>{children}</View></View> }
function ProfileField({ colors, label, value }: any) { return <View style={[styles.profileField, { borderColor: colors.border }]}><Text style={{ color: colors.muted, fontSize: 12 }}>{label}</Text><Text selectable style={{ color: colors.text, fontSize: 14 }}>{value}</Text></View> }
function Row({ colors, icon, label, detail, onPress, right }: any) { return <Pressable disabled={!onPress} onPress={onPress} style={({ pressed }) => [styles.row, pressed && onPress && styles.pressed]}><Ionicons name={icon} size={21} color={colors.text} /><View style={{ flex: 1 }}><Text style={[styles.label, { color: colors.text }]}>{label}</Text>{detail ? <Text style={[styles.detail, { color: colors.muted }]} numberOfLines={1}>{detail}</Text> : null}</View>{right || (onPress ? <Ionicons name="chevron-forward" size={18} color={colors.muted} /> : null)}</Pressable> }
function message(error: unknown) { return error instanceof Error ? error.message : "发生未知错误" }
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 105, gap: 20 }, pageHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, title: { fontSize: 26, fontWeight: "700" }, section: { gap: 7 }, sectionTitle: { fontSize: 12, fontWeight: "600", textTransform: "uppercase" }, card: { borderWidth: 1, borderRadius: 14, overflow: "hidden" }, row: { minHeight: 64, paddingHorizontal: 14, alignItems: "center", flexDirection: "row", gap: 12 }, label: { fontSize: 15, fontWeight: "500" }, detail: { fontSize: 12, marginTop: 3 }, choices: { flexDirection: "row", gap: 8, marginBottom: 10 }, choice: { flex: 1, height: 62, borderWidth: 1, borderRadius: 12, alignItems: "center", justifyContent: "center", gap: 3 }, logout: { height: 48, borderRadius: 12, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8 }, pressed: { opacity: 0.58, transform: [{ scale: 0.985 }] }, sheetContent: { gap: 14, paddingBottom: 16 }, codeButton: { minHeight: 44, borderRadius: 10, paddingHorizontal: 12, justifyContent: "center" }, profileField: { minHeight: 56, borderBottomWidth: StyleSheet.hairlineWidth, justifyContent: "center", gap: 4 } })
