import { useCallback, useEffect, useState } from "react"
import { Alert, FlatList, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native"
import { request } from "../api"
import type { Palette } from "../theme"
import { Action, Choice, Input, Sheet, Top } from "./TasksPage"

type Workspace = Record<string, any>
export default function WorkspacesPage({ colors, onBack }: { colors: Palette; onBack: () => void }) {
  const [items, setItems] = useState<Workspace[]>([]); const [agents, setAgents] = useState<any[]>([]); const [models, setModels] = useState<string[]>([]); const [editor, setEditor] = useState<Workspace | null>(null); const [form, setForm] = useState<any>({ name: "", location: "server", device_id: "", path: "", model: "", agent: "" }); const [file, setFile] = useState<any | null>(null); const [content, setContent] = useState(""); const [error, setError] = useState("")
  const load = useCallback(async () => { try { const [data, nextAgents, catalog] = await Promise.all([request<any>("/user/advanced-chat/workspaces"), request<any[]>("/user/advanced-chat/agents"), request<any[]>("/user/catalog")]); setItems(Array.isArray(data?.workspaces) ? data.workspaces : Array.isArray(data) ? data : []); setAgents(Array.isArray(nextAgents) ? nextAgents : []); setModels([...new Set((Array.isArray(catalog) ? catalog : []).flatMap(item => item.models || []))]) } catch (e) { setError(message(e)) } }, [])
  useEffect(() => { void load() }, [load])
  const open = (item?: Workspace) => { setEditor(item || {}); setForm(item ? { name: item.name || "", location: item.location || "server", device_id: item.device_id || "", path: item.path || "", model: item.model || "", agent: item.agent || "" } : { name: "", location: "server", device_id: "", path: "", model: models[0] || "", agent: agents[0]?.id || "" }) }
  const saveWorkspace = async () => { if (!form.name.trim() || !form.model || !form.agent) { setError("请填写名称、模型和智能体"); return } try { await request(editor?.id ? `/user/advanced-chat/workspaces/${encodeURIComponent(editor.id)}` : "/user/advanced-chat/workspaces", { method: editor?.id ? "PUT" : "POST", body: form }); setEditor(null); await load() } catch (e) { setError(message(e)) } }
  const remove = (item: Workspace) => Alert.alert("删除工作区", `确定删除“${item.name}”及其中文件？`, [{ text: "取消", style: "cancel" }, { text: "删除", style: "destructive", onPress: async () => { try { await request(`/user/advanced-chat/workspaces/${encodeURIComponent(item.id)}`, { method: "DELETE" }); await load() } catch (e) { setError(message(e)) } } }])
  const openFile = (workspace: Workspace, nextFile: any) => { setEditor(workspace); setFile(nextFile); setContent(nextFile.content || "") }
  const saveFile = async () => { if (!editor?.id || !file?.id) return; try { await request(`/user/advanced-chat/workspaces/${encodeURIComponent(editor.id)}/files/${encodeURIComponent(file.id)}`, { method: "PUT", body: { name: file.name, content } }); setFile({ ...file, content }); await load() } catch (e) { setError(message(e)) } }
  const createFile = async () => { if (!editor?.id) return; const name = `未命名-${Date.now()}.md`; try { const created = await request<any>(`/user/advanced-chat/workspaces/${encodeURIComponent(editor.id)}/files`, { method: "POST", body: { name, content: "# 新文档\n\n" } }); setFile(created); setContent(created.content || "# 新文档\n\n"); await load() } catch (e) { setError(message(e)) } }
  const workspace = editor?.id ? items.find(item => item.id === editor.id) || editor : null
  if (file && workspace) return <View style={styles.root}><Top colors={colors} title={file.name} onBack={() => { setFile(null); setContent("") }} right="" /><Text style={{ color: colors.muted, paddingHorizontal: 14, paddingTop: 8 }}>{workspace.name}</Text><Input colors={colors} label="内容" value={content} onChangeText={setContent} multiline style={styles.editor} /><View style={styles.fileActions}><Action colors={colors} title="保存文件" onPress={saveFile} /><Action colors={colors} title="新建文件" onPress={createFile} /></View></View>
  return <View style={styles.root}><Top colors={colors} title="工作区" onBack={onBack} right="add" onRight={() => open()} />{error ? <Text style={{ color: colors.destructive, padding: 12 }}>{error}</Text> : null}<FlatList data={items} keyExtractor={item => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={{ color: colors.muted }}>暂无工作区</Text>} renderItem={({ item }) => <View style={[styles.row, { borderColor: colors.border, backgroundColor: colors.card }]}><Pressable style={{ flex: 1 }} onPress={() => open(item)} onLongPress={() => remove(item)}><Text style={{ color: colors.text, fontWeight: "600" }}>{item.name}</Text><Text style={{ color: colors.muted, fontSize: 12 }}>{item.location === "server" ? "服务端" : "设备"} · {item.path}</Text></Pressable><ScrollView horizontal contentContainerStyle={styles.files}>{(item.files || []).map((entry: any) => <Pressable key={entry.id} onPress={() => openFile(item, entry)} style={[styles.file, { backgroundColor: colors.input }]}><Text style={{ color: colors.text }}>{entry.name}</Text></Pressable>)}</ScrollView></View>} /><Modal visible={Boolean(editor && !file)} transparent animationType="slide"><Sheet colors={colors} title={editor?.id ? "编辑工作区" : "新建工作区"} onClose={() => setEditor(null)}><ScrollView contentContainerStyle={styles.form}><Input colors={colors} label="工作区名称" value={form.name} onChangeText={(v: string) => setForm({ ...form, name: v })} /><Choice colors={colors} label="存放位置" values={["server", "device"]} labels={["服务端", "连接器设备"]} value={form.location} onChange={(v: string) => setForm({ ...form, location: v })} />{form.location === "device" ? <Input colors={colors} label="设备 ID" value={form.device_id} onChangeText={(v: string) => setForm({ ...form, device_id: v })} /> : null}<Input colors={colors} label="路径" value={form.path} onChangeText={(v: string) => setForm({ ...form, path: v })} /><Choice colors={colors} label="模型" values={models} value={form.model} onChange={(v: string) => setForm({ ...form, model: v })} /><Choice colors={colors} label="智能体" values={agents.map(item => item.id)} labels={agents.map(item => item.name)} value={form.agent} onChange={(v: string) => setForm({ ...form, agent: v })} /><Action colors={colors} title="保存工作区" onPress={saveWorkspace} /></ScrollView></Sheet></Modal></View>
}
function message(error: unknown) { return error instanceof Error ? error.message : "发生未知错误" }
const styles = StyleSheet.create({ root: { flex: 1 }, list: { padding: 16, gap: 10 }, row: { borderWidth: 1, borderRadius: 12, padding: 12, gap: 10 }, files: { gap: 7 }, file: { height: 32, borderRadius: 8, paddingHorizontal: 9, justifyContent: "center" }, form: { gap: 14, paddingBottom: 18 }, editor: { minHeight: 350, margin: 14 }, fileActions: { padding: 14, gap: 10 } })
