import { execFileSync } from "node:child_process";
import { cpSync, mkdirSync, rmSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const dir = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(dir, "../..");
const web = path.join(repo, "web");
rmSync(path.join(web, "src"), { recursive: true, force: true });
cpSync(path.join(dir, "frontend"), path.join(web, "src"), { recursive: true });
execFileSync(process.platform === "win32" ? "yarn.cmd" : "yarn", ["build:web"], { cwd: web, stdio: "inherit" });
const output = path.join(dir, "dist", "web");
rmSync(output, { recursive: true, force: true });
mkdirSync(path.dirname(output), { recursive: true });
cpSync(path.join(web, "dist"), output, { recursive: true });
