import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Save } from "lucide-react"
import { useMemo, useState } from "react"
import { api, Button } from "@velocelab/dashboard/frontend"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
interface ManagedPlugin { name: string; title: string }
interface PluginUpdate { name: string; currentVersion: string; availableVersion: string; versions: string[]; fixedVersion?: string | null; registryAvailable: boolean; packageFound: boolean }
function options(item: PluginUpdate) { return [...new Set([item.currentVersion, ...item.versions].filter(Boolean))] }
export default function UpdateCheckerPage() { const client = useQueryClient(); const [draft, setDraft] = useState<Record<string, string>>({}); const installed = useQuery<{ plugins: ManagedPlugin[] }>({ queryKey: ["settings", "plugins", "updates"], queryFn: async () => (await api.get("/settings/plugins")).data }); const names = useMemo(() => installed.data?.plugins.map((plugin) => plugin.name) || [], [installed.data]); const check = useQuery<{ plugins: PluginUpdate[] }>({ queryKey: ["update-checker", "plugins", names], enabled: Boolean(names.length), queryFn: async () => (await api.post("/user/update-checker/check", { names })).data }); const save = useMutation({ mutationFn: async () => api.post("/user/update-checker/pins", { pins: draft }), onSuccess: () => { void client.invalidateQueries({ queryKey: ["update-checker"] }) } }); const title = new Map((installed.data?.plugins || []).map((plugin) => [plugin.name, plugin.title])); return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-3xl font-bold">插件更新</h1><p className="mt-2 text-sm text-muted-foreground">从 npm 检查版本，并保存当前用户的版本固定选择。</p></div><Button className="gap-2" disabled={save.isPending || !Object.keys(draft).length} onClick={() => save.mutate()}><Save size={16} />保存更改</Button></div><div className="space-y-3">{(check.data?.plugins || []).map((item) => { const list = options(item); const value = draft[item.name] || item.fixedVersion || item.currentVersion || list[0]; const update = item.packageFound && item.availableVersion !== item.currentVersion; return <Card key={item.name}><CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle className="flex items-center gap-2">{title.get(item.name) || item.name}{update && <span className="rounded bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary">有更新</span>}</CardTitle><p className="mt-1 font-mono text-xs text-muted-foreground">{item.name}</p></div><Select value={value} onValueChange={(version) => setDraft((current) => ({ ...current, [item.name]: version }))} disabled={!list.length}><SelectTrigger className="w-full sm:w-52"><SelectValue /></SelectTrigger><SelectContent>{list.map((version) => <SelectItem key={version} value={version}>{version}{version === item.currentVersion ? "（当前）" : ""}{version === item.availableVersion ? "（最新）" : ""}</SelectItem>)}</SelectContent></Select></CardHeader><CardContent className="text-sm text-muted-foreground">{!item.registryAvailable ? "npm registry 暂时不可用。" : !item.packageFound ? `当前版本：${item.currentVersion || "未知"}；该包未发布到 npm。` : `当前版本：${item.currentVersion}；npm 最新：${item.availableVersion}`}{item.fixedVersion ? ` 已固定：${item.fixedVersion}` : ""}</CardContent></Card> })}</div></div> }
