import { createRequire } from "node:module";
import { readFile } from "node:fs/promises";
import { Context, Database, Schema, Session } from "yumeri";
import "@velocelab/dashboard";

export const depend = ["database", "dashboard"];
export const provide = ["update-checker"];
export interface UpdateCheckerConfig { registryBaseUrl: string; requestTimeoutMs: string; maxVersionsPerPlugin: string }
export const config: Schema<UpdateCheckerConfig> = Schema.object({
  registryBaseUrl: Schema.string("npm registry base URL").key("update-checker.config.registryBaseUrl").default("https://registry.npmjs.org"),
  requestTimeoutMs: Schema.string("npm update check timeout milliseconds").key("update-checker.config.requestTimeoutMs").default("20000"),
  maxVersionsPerPlugin: Schema.string("Maximum npm versions shown per plugin").key("update-checker.config.maxVersionsPerPlugin").default("100"),
});
type Pin = { id?: number; user_id: number; plugin_name: string; version: string; updated_at: string };
declare module "@yumerijs/types" { interface Tables { user_plugin_version_pins: Pin } }
const resolve = createRequire(import.meta.url).resolve;
function user(session: Session) { return (session.properties.user as { id?: number } | undefined)?.id }
function base(raw: string) { const value = new URL(raw); if (!/^https?:$/.test(value.protocol)) throw Error("npm registry must use HTTP(S)"); return value.toString().replace(/\/$/, "") }
function validPackageName(name: string) { return name.length > 0 && name.length <= 214 && !/[\\\0\s]/.test(name) && (name.startsWith("@") ? /^@[a-z0-9][a-z0-9._-]*\/[a-z0-9][a-z0-9._-]*$/i.test(name) : /^[a-z0-9][a-z0-9._-]*$/i.test(name)) }
async function installedVersion(name: string) { if (!validPackageName(name)) return ""; try { const file = resolve(`${name}/package.json`); const parsed = JSON.parse(await readFile(file, "utf8")); return String(parsed.version ?? ""); } catch { return "" } }
async function npmMetadata(cfg: UpdateCheckerConfig, name: string) { const response = await fetch(`${base(cfg.registryBaseUrl)}/${encodeURIComponent(name)}`, { signal: AbortSignal.timeout(Math.max(1000, Number(cfg.requestTimeoutMs) || 20000)), headers: { accept: "application/vnd.npm.install-v1+json" } }); if (response.status === 404) return null; if (!response.ok) throw Error(`npm registry returned HTTP ${response.status}`); return await response.json() as any }
function sortVersions(values: string[]) { return [...new Set(values)].sort((left, right) => right.localeCompare(left, undefined, { numeric: true, sensitivity: "base" })) }
export async function apply(ctx: Context, cfg: UpdateCheckerConfig) {
  const db = ctx.component.database as Database;
  await db.extend("user_plugin_version_pins", { id: { type: "integer", autoIncrement: true }, user_id: { type: "integer", nullable: false }, plugin_name: { type: "string", nullable: false }, version: { type: "string", nullable: false }, updated_at: "timestamp" }, { unique: [["user_id", "plugin_name"]] });
  ctx.component.dashboard.addEntry({ dev: new URL("../frontend/index.tsx", import.meta.url).pathname, prod: new URL("./frontend/update-checker.js", import.meta.url).pathname, plugin: "update-checker" });
  ctx.route("/api/user/update-checker/check").methods("POST").action(async (session: Session) => { const userId = user(session); if (userId === undefined) return; const body = await session.parseRequestBody() as any; const rawNames = (Array.isArray(body?.names) ? body.names : []).map((value: unknown) => String(value)).filter(validPackageName) as string[]; const names = [...new Set(rawNames)].slice(0, 200); const pins: any[] = await db.select("user_plugin_version_pins", { user_id: userId }); const pinMap = new Map(pins.map((pin) => [pin.plugin_name, pin.version])); const maxVersions = Math.max(2, Number(cfg.maxVersionsPerPlugin) || 100); const plugins = await Promise.all(names.map(async (name) => { const currentVersion = await installedVersion(name); try { const metadata = await npmMetadata(cfg, name); if (!metadata) return { name, currentVersion, availableVersion: "", versions: currentVersion ? [currentVersion] : [], fixedVersion: pinMap.get(name) || null, registryAvailable: true, packageFound: false }; const all = sortVersions(Object.keys(metadata.versions ?? {})); const availableVersion = String(metadata["dist-tags"]?.latest ?? all[0] ?? ""); const versions = sortVersions([availableVersion, currentVersion, ...all]).slice(0, maxVersions); return { name, currentVersion, availableVersion, versions, fixedVersion: pinMap.get(name) || null, registryAvailable: true, packageFound: true }; } catch { return { name, currentVersion, availableVersion: "", versions: currentVersion ? [currentVersion] : [], fixedVersion: pinMap.get(name) || null, registryAvailable: false, packageFound: false }; } })); session.respond({ plugins }, "json"); });
  ctx.route("/api/user/update-checker/pins").methods("POST").action(async (session: Session) => { const userId = user(session); if (userId === undefined) return; const body = await session.parseRequestBody() as any; const pins = body?.pins && typeof body.pins === "object" ? body.pins : {}; for (const [pluginName, version] of Object.entries(pins)) { const name = String(pluginName); const selected = String(version).slice(0, 100); if (!validPackageName(name) || !selected) continue; const existing = await db.selectOne("user_plugin_version_pins", { user_id: userId, plugin_name: name }); if (existing) await db.update("user_plugin_version_pins", { user_id: userId, plugin_name: name }, { version: selected, updated_at: new Date().toISOString() }); else await db.create("user_plugin_version_pins", { user_id: userId, plugin_name: name, version: selected, updated_at: new Date().toISOString() } as any); } session.respond({ ok: true }, "json"); });
}
